# -*- coding: utf-8 -*-
"""Ellen Dayane Vivas Rosa Mezaki - 211_Vetor_n.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x-_4OITHJg3iZNrrLMHZWcSdlnZb97Fj

#**EXERCÍCIOS SOBRE VETOR**

### 1. Faça um programa que calcule e apresente a média de idades de uma sala de 35 alunos.​​
"""

vetor_idade = []
soma_idade = 0
for i in range(35):
    vetor_idade.append(int(input('Informe a idade: ')))
    soma_idade = soma_idade + vetor_idade[i]

media = soma_idade / len(vetor_idade)    
print('valor da variável i: ',i, 'Quantidade de elementos: ',len(vetor_idade), 'Média de idades: ',media)

"""### 2. Faça um programa que calcule e apresente a média de alturas de uma sala de 35 alunos. Informe também quantos alunos **e** quais (índice/posição) são os que possuem idade superior a 25 anos.​ Use dois vetores, um para altura e outro para idade. Não use nenhuma função pronta da linguagem Python.

"""

vetor_altura = []
vetor_idade = []
soma_altura = 0
alunos = 0
for alunos in range(35):
    vetor_altura.append(float(input('Informe a altura: ')))
    soma_altura += vetor_altura[alunos]
    vetor_idade.append(int(input('Informe a idade: ')))
    alunos = alunos + 1
media = soma_altura / len(vetor_altura)
print(f'A média de altura dos alunos é: {media:.2f}')
    
soma = 0
for alunos in range(35):
    if vetor_idade[alunos] > 25:
        soma = soma + 1
        alunos = alunos + 1
        print('O aluno de número', alunos, 'possui mais de 25 anos')
print('A quantidade de alunos maiores de 25 anos são: ',soma)

"""### 3. Faça um programa que carregue um vetor de dez elementos que contenha o nome de pessoas e outro que contenha o peso, encontre qual a pessoa mais gorda e mais magra e apresente o nome o peso das mesmas.​ Use dois vetores, um para peso e outro para nome. Não use nenhuma função pronta da linguagem Python."""

vet_peso = []  # declarar a variavel vetor vazia, deve ser antes do laço de repetição
vet_nome = []
for i in range(10):
    vet_nome.append(str(input('Digite o nome: ')))
    vet_peso.append(float(input('Digite o peso: ')))
    if i == 0:
        gordo = vet_peso[i]
        magro = vet_peso[i]
        nome_gordo = vet_nome[i]
        nome_magro = vet_nome[i]
    if vet_peso[i] > gordo:
        gordo = vet_peso[i]
        nome_gordo = vet_nome[i]
    if vet_peso[i] < magro:
        magro = vet_peso[i]
        nome_magro = vet_nome[i]
print(nome_gordo, 'possui',gordo,'kg e é o mais pesado')
print(nome_magro, 'possui',magro,'kg e é o mais magro')
for i in range(10):
    print('Nome: ',vet_nome[i],'\tpeso: ', vet_peso[i],'kg')

"""### 4. Faça um programa que carregue um vetor com a média de dez alunos, calcule e mostre a MÉDIA DA SALA e quantos alunos estão acima e abaixo da média da sala."""

media_aluno = [] 
media_sala = 0
acima_media = 0
abaixo_media = 0
for i in range(10):
    media_aluno.append(float(input('Informe a média do aluno: ')))
    media_sala = media_sala + media_aluno[i]
    media = media_sala / len(media_aluno)
print('A média da sala é: ', media)
for i in range(10):
    if media_aluno[i] > media:
        acima_media += 1
    elif media_aluno[i] < media:
        abaixo_media += 1
print('Alunos abaixo da média',abaixo_media)  
print('Alunos acima da média',acima_media)

"""### 5. Faça um programa que carregue um vetor de oito elementos numéricos inteiros, calcule e mostre os números pares e suas respectivas índices/posições. Não use nenhuma função pronta da linguagem Python.

"""

numeros = [] 
numero_par = 0
for num in range(8):
    numeros.append(int(input('Informe um número inteiro: ')))
    
for num in range(8):
    if numeros[num] % 2 == 0:
        print('É um número par: ',numeros[num])
        print('E esta no índice: ', num)

"""### 6. Faça um programa que carregue um vetor com dez nomes e faça uma verificação se um determinado nome esta nesse vetor. Não use nenhuma função pronta da linguagem Python.

"""

nomes = [] 
for name in range(10):
    nomes.append(str(input('Informe um nome: ')))
    
nome = str(input('Informe um nome para ser verificado: '))

if nome in nomes:
    print('O nome',nome, 'esta na lista')
else:    
    print('O nome',nome, 'não esta na lista')

"""### 7. Faça um algoritmo que calcule e apresente a média de alturas superior a 1,80 de 10 alunos. Informe também quantos e quais (índice/posição) são os alunos. Não use nenhuma função pronta da linguagem Python.

"""

vetor_altura = []
soma_altura = 0
for alunos in range(10):
    vetor_altura.append(float(input('Informe a altura: ')))
   
soma = 0
for alunos in range(10):
    if vetor_altura[alunos] > 1.80:
        soma_altura += vetor_altura[alunos]
        soma = soma + 1
        print('O aluno de número', alunos, 'possui mais 1.80 cm de altura')
media = soma_altura / soma        
print(f'A média de altura dos alunos maiores que 1.80 cm é: {media:.2f}')        
print('A quantidade de alunos maiores que 1.80 cm: ',soma)

"""### 8. Criar um algoritmo que a partir de um vetor de 10 elementos inteiros, crie outros dois vetores que receberão os elementos positivos e negativos e ao final apresente-os. Não use nenhuma função pronta da linguagem Python.

"""

numero = []
positivo = []
negativo = []
for i in range(4):
    numero.append(int(input('Informe um valor: ')))
    if numero[i] >= 0:
        positivo.append(numero[i])
    else:
        negativo.append(numero[i])
print(numero)
print(positivo)
print(negativo)

"""### 9. Criar um algoritmo que leia dados para um vetor de 100 elementos inteiros, imprimir o maior, o menor, o percentual de números pares e a média dos elementos do vetor. Obs.: percentual = quantidade contada * 100 / quantidade total. Não use nenhuma função pronta da linguagem Python.

"""

vetor = []
par = 0
percentual_par = 0
soma = 0
for i in range(100):
    vetor.append(int(input('Informe um número inteiro: ')))
    soma += vetor[i]
    if i == 0:
        maior = menor = vetor[i]
    if vetor[i] > maior:
        maior = vetor[i]
    elif vetor[i] < menor:
        menor = vetor[i]
    if vetor[i] % 2 == 0:
        par += 1
percentual_par = (par * 100) / len(vetor)
media = soma / len(vetor)
print('O maior número sera: ',maior, 'e o menor número sera: ',menor)
print('O percentual de números pares é: ',percentual_par,'%')
print('A média de elementos do vetor é: ',media)

"""### 10. Faça um programa que:

* preencha um vetor com seis elementos numéricos inteiros. 

**Calcule e mostre:**

* todos os números pares;
* a quantidade de números pares;
* todos os números ímpares;
* a quantidade de números ímpares
"""

vetor = []
vetor_p = []
vetor_i = []
soma_par = 0
soma_impar = 0
for i in range(6):
    vetor.append(int(input('Informe um número inteiro: ')))
    if vetor[i] % 2 == 0:
        vetor_p.append(vetor[i])
        soma_par += 1
    else:
        vetor_i.append(vetor[i])
        soma_impar += 1

print('Os números pares são: ', vetor_p)
print('A soma de números pares é: ',soma_par)
print('Os números ímpares são: ', vetor_i) 
print('A soma de números ímpares é: ',soma_impar)

"""### 11. Faça um programa que:

* preencha um vetor com sete números inteiros

**Calcule e mostre:**

* os números múltiplos de 2;
* os números múltiplos de 3;
* os números múltiplos de 2 e de 3.
"""

vetor = []
mult_2 = 0
mult_3 = 0
multiplos = 0
for i in range(7):
    vetor.append(int(input('Informe um número inteiro: ')))
    if vetor[i] % 2 == 0:
        mult_2 = vetor[i]
        print('O número ',mult_2, 'é multiplo de 2')
    elif vetor[i] % 3 == 0:
        mult_3 = vetor[i]
        print('O número ',mult_3, 'é multiplo de 3')
    elif vetor[i] % 2 == 0 and vetor[i] % 3 == 0:
        multiplos = mult_2 + mult_3
        print('O número ',multiplos, 'é multiplo de 2 e 3')

"""### 12. Faça um programa que:

* preencha um vetor com quinze elementos inteiros
* verifique a existência de elementos iguais a 30, mostrando os índices/posições em que apareceram.
"""

vetor = []
for i in range(15):
    vetor.append(int(input('Informe um número: ')))
    if vetor[i] == 30:
        print('O número 30 está no índice: ', i)

"""### 13. Faça um programa que:

* preencha um vetor com dez números reais

**Calcule e mostre:**

* a quantidade de números negativos
* a soma dos números positivos desse *vetor*
* não use nenhuma função pronta da linguagem Python
"""

vetor = []
cont_negativo = 0
soma_positivo = 0
for i in range(10):
    vetor.append(float(input('Informe um número: ')))
    if vetor[i] < 0:
        cont_negativo += 1
    else:
        soma_positivo += vetor[i]

print('A quantidade de números negativos é: ',cont_negativo)
print('A soma de números positivos é: ',soma_positivo)

"""### 14. Faça um programa que:

* receba dez números inteiros e armazene-os em um vetor
* classifique os números em dois vetores, um com números pares e o outra com os ímpares
* não use nenhuma função pronta da linguagem Python
"""

vetor = []
vetor_par = []
vetor_impar = []
for i in range(10):
    vetor.append(int(input('Informe um número inteiro: ')))
    if vetor[i] % 2 == 0:
        vetor_par.append(vetor[i])
    else:
        vetor_impar.append(vetor[i])

print('Vetor par: ', vetor_par)
print('Vetor ímpar: ', vetor_impar)

"""### 15. Faça um programa que:

* preencha um vetor com quinze números

**Determine e mostre:**

* o maior número e a posição por ele ocupada no vetor
* o menor número e a posição por ele ocupada no vetor
* Não use nenhuma função pronta da linguagem Python
"""

vetor = []
maior_num = 0
menor_num = 0
for i in range(10):
    vetor.append(float(input('Informe um número: ')))
    if i == 0:
        maior_num = menor_num = vetor[i]
        maior = i
        menor = i
    else:    
        if vetor[i] > maior_num:
            maior_num = vetor[i]
            maior = i
        elif vetor[i] < menor_num:
            menor_num = vetor[i] 
            menor = i

print('O maior número sera: ',maior_num, 'e seu índice é: ', maior)
print('E o menor número sera: ',menor_num, 'e seu índice é: ', menor)

"""### 16. Faça um programa que:

* preencha dois vetores com de dez numeros cada
* preencha um terceiro vetor com os números dos dois vetores anteriores ordenados em ordem crescente

"""

vetor_1 = []
vetor_2 = []
vetor_3 = []
for i in range(10):
    vetor_1.append(float(input('Informe um número para a lista 1: ')))
    vetor_2.append(float(input('Informe um número para a lista 2: ')))
vetor_3 = vetor_1 + vetor_2
vetor_3.sort() 
print(f'A lista ordenada em ordem crescente é: ', vetor_3)

"""### 17. Faça um programa que:

* carregue dois vetores com 10 números cada
* faça a multiplicação dos números na mesma posição
* o resultado deverá ser adicionada em um terceiro vetor
* não use nenhuma função pronta da linguagem Python
"""

vetor_1 = []
vetor_2 = []
vetor_3 = []
for i in range(10):
    vetor_1.append(float(input('Informe um número para a lista 1: ')))
    vetor_2.append(float(input('Informe um número para a lista 2: ')))
    vetor_3.append(float(vetor_1[i]) * (vetor_2[i]))  
print(f'Após a multiplicação temos a seguinte lista de números: ', vetor_3)

"""### 18. Faça um programa que:

* leia um vetor de 10 números inteiros
* exiba na tela os números positivos e seus respectivos índices.
* não use nenhuma função pronta da linguagem Python
"""

vetor = []
for i in range(10):
    vetor.append(int(input('Informe um número inteiro: ')))

for i in range(10):
    if vetor[i] > 0:
        print(f'O número inteiro positivo {vetor[i]} esta no índice {i}')

"""### 19. Faça um programa que:

* insira dez números inteiros em um vetor
* crie um segundo vetor, substituindo os números multiplos de 3 por "999""
* exiba os dois vetores
* não use nenhuma função pronta da linguagem Python
"""

vetor = []
for i in range(10):
    vetor.append(int(input('Informe um número inteiro: ')))

vetor_novo = []
for i in range (len(vetor)):
    if vetor[i] % 3 == 0:
        vetor_novo.append(int(999))
    else:
        vetor_novo.append(vetor[i])    
print(vetor)
print(vetor_novo)

"""### 20. Faça um programa que:
* adicione 10 numeros inteiros em um vetor de nome A
* remova todos os numeros menores que 0 do vetor A e os adicione no vetor B
* exiba os dois vetores A e B
"""

vetor_a = []
vetor_b = []
 
for i in range(10):
    vetor_a.append(int(input("Informe um número inteiro: ")))
 
for elemento in vetor_a:
    if elemento < 0:
        vetor_a.remove(elemento)
        vetor_b.append(elemento)
 
print("Vetor A: ",vetor_a)
print("Vetor B: ",vetor_b)
