# -*- coding: utf-8 -*-
"""Ellen Dayane Vivas Rosa Mezaki - 211_Alg_noite.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xjpOLuz7k9CxvYq_Y_CicxSPGXEllUtK

# Exercícios para construir programas com ENTRADA, PROCESSAMENTO e SAÍDA

### 1. Faça um programa que leia um número, multiplique ele por 2 e apresente o resultado.
      LEIA numero
      resultado = numero * 2
      ESCREVA resultado
"""

#entrada
numero = int(input('Informe um valor: '))
#processamento
resultado = numero * 2
#saída
print('O resultado é',resultado)

"""### 2. Faça um programa que:
* receba quatro números inteiros
* calcule e mostre a soma desses números.

    LEIA n1, n2, n3, n4
    
    soma = n1 + n2 + n3 + n4
  
    ESCREVA soma

"""

#entrada
n1 = int(input('Digite o primeiro número '))
n2 = int(input('Digite o segundo número '))
n3 = int(input('Digite o terceiro número '))
n4 = int(input('Digite o quarto número '))
#processamento
soma = n1 + n2 + n3 + n4
#saída
print('A soma é', soma)

"""### 3. Faça um programa que receba três notas, calcule e mostre a média aritmética.
      LEIA nota1, nota2, nota3
      media = (nota1 + nota2 + nota3) / 3
      ESCREVA media
      
"""

#entrada
nota1 = float(input('Digite a primeira nota '))
nota2 = float(input('Digite a segunda nota '))
nota3 = float(input('Digite a terceira nota '))
#processamento
media = (nota1 + nota2 + nota3) / 3
#saída
print('A média é', media)

"""### 4. Faça um programa que:
* receba o salário de um funcionário
* calcule e mostre o novo salário, sabendo-se que este sofreu um aumento de 25%.

      LEIA salario
      novoSalario = salario + (salario * 25 / 100)
      ESCREVA novoSalario
"""

#entrada
salario = float(input('Digite o valor do salário '))
#processamento
novosalario = salario + (salario * 25 / 100)
#saída
print('o novo salario é', novosalario)

"""### 5. Faça um programa que receba o salário de um funcionário e o percentual de aumento, calcule e mostre o valor do aumento e o novo salário.

      LEIA salario, percentual
      aumento = salario * percentual/100
      ESCREVA aumento
      novo_salario = salario + aumento
      ESCREVA novo_salario
"""

# entrada
salario = float(input('Digite o valor do salário '))
percentual_aumento = float(input('Digite o valor do percentual de aumento '))
#procedimento
aumento = salario * percentual_aumento / 100
novo_salario = salario + aumento
#saída
print('o aumento é', aumento)
print('o novo salário é', novo_salario)

"""### 6. Faça um programa que receba o salário base de um funcionário, calcule e mostre o salário a receber, sabendo-se que o funcionário tem gratificação de 5% sobre o salário base e paga imposto de 7% também sobre o salário base.

    LEIA salario
    gratificacao = salario * 5 / 100
    imposto = salario * 7 / 100
    salario_a_receber = salario + gratificacao − imposto
    ESCREVA salario_a_receber
"""

# entrada
salario_base = float(input('Informe o salário base '))
#procedimento
gratificacao = salario_base * 5 / 100
imposto = salario_base * 7 / 100
salario_a_receber = salario_base + gratificacao - imposto
#saida
print('o salário a receber é', salario_a_receber)

"""### 7. Faça um programa que receba o salário base de um funcionário, calcule e mostre seu salário a receber, sabendo-se que o funcionário tem gratificação de 50,00 sobre o salário base e paga imposto que deve ser lido e é aplicado sobre o salário base.

    LEIA salario, perImposto
    imposto = salario * perImposto / 100
    salario_a_receber = salario + 50 - imposto
    ESCREVA salario_a_receber
"""

#entrada
salario = float(input('Informe o salário: '))
perimposto = float(input('Informe o valor do imposto: '))
#processamento
imposto = salario * perimposto / 100
salario_a_receber = salario + 50 - imposto
#saída
print('O salário a receber é:', salario_a_receber)

"""### 8. Faça um programa que receba o valor de um depósito e o valor da taxa de juros, calcule e mostre o valor do rendimento e o valor total depois do rendimento de um mês.

      LEIA deposito, taxa
      rendimento = deposito * taxa / 100
      total = deposito + rendimento
      ESCREVA rendimento
      ESCREVA total
"""

#entrada
deposito = float(input('O valor do depósito é: '))
taxa = float(input('O valor da taxa é: '))
#processamento
rendimento = deposito * taxa / 100
total = deposito + rendimento
#saída
print('O rendimento é:', rendimento)
print('O valor total é:', total)

"""### 9. Faça um programa que calcule e mostre a área de um triângulo. Sabe-se que: Área = (base * altura) / 2.

    LEIA base, altura
    area = (base * altura) / 2
    ESCREVA area
"""

#entrada
base = float(input('Informe o tamanho da base do triângulo: '))
altura = float(input('Informe o altura do triângulo: '))
#processamento
area = (base * altura) / 2
#saída
print('A área do triângulo é:', area)

"""### 10. Faça um programa que calcule e mostre a área de um círculo. Sabe-se que: Área = p * raio 2 (o número 2 significa potência, ou seja, raio é elevado ao quadrado)

    LEIA raio
    area = 3.1415 * raio ** 2
    ESCREVA area
"""

#entrada
raio = float(input('O valor do raio é: '))
#processamento
area = 3.1415 * raio ** 2
#saída
print('A área do círculo é:', area)

"""### 11. Faça um programa que receba um número positivo e maior que zero, calcule e mostre:
* O número digitado ao quadrado
* O número digitado ao cubo
* A raiz do número digitado
* A raiz cúbica do número digitado

      LEIA numero
      quadrado = numero ** 2
      cubo = numero ** 3
      raiz_quadrada = numero ** ½ (meio, ou 0.5)
      raiz_cubica = numero ** ⅓ (um terço, ou 0.33)
      ESCREVA quadrado, cubo, raiz_quadrada, raiz_cubica
"""

#entrada
numero = int(input('Digite um número: '))
#processamento
quadrado = numero ** 2
cubo = numero ** 3
raiz_quadrada = numero ** (1/2)
raiz_cubica = numero ** (1/3)
#saída
print('O valor do número ao quadrado é:', quadrado)
print('O valor do número ao cubo é:', cubo)
print('A raiz quadrada do número é:', raiz_quadrada)
print('A raiz cúbica do número é:', raiz_cubica)

"""### 12. Faça um programa que receba dois números maiores que zero, calcule e mostre um elevado ao outro.

      LEIA numero1, numero2
      numero1_elevado_numero2 = numero1 ** numero2
      numero2_elevado_numero1 = numero2 ** numero1
      ESCREVA numero1_elevado_numero2, numero2_elevado_numero1
"""

#entrada
numero1 = float(input('Digite um número: '))
numero2 = float(input('Digite um número: '))
#processamento
numero1_elevado_numero2 = numero1 ** numero2
numero2_elevado_numero1 = numero2 ** numero1
#saida
print('O valor do número 1 elevado ao número 2 é:', numero1_elevado_numero2)
print('O valor do número 2 elevado ao número 1 é:', numero2_elevado_numero1)

"""### 13. Sabe-se que:

* pé = 12 polegadas
* 1 jarda = 3 pés
* 1 milha = 1,760 jarda

Faça um programa que receba uma medida em pés, faça as conversões a seguir e mostre os resultados.

* Polegadas;
* Jardas;
* Milhas.

      LEIA pes
      polegadas = pes * 12
      jardas = pes / 3
      milhas = jardas / 1760
      ESCREVA polegadas, jardas, milhas
"""

#entrada
pes = float(input('A medida em pés é: '))
#processamento
polegadas = pes * 12
jardas = pes / 3 
milhas = jardas / 1760
#saída
print('O valor em polegadas é: ', polegadas)
print('O valor em jardas é: ', jardas)
print('O valor em milhas é: ', milhas)

"""### 14. Faça um programa que receba o ano de nascimento de uma pessoa e o ano atual, calcule e mostre:
* a idade dessa pessoa;
* quantos anos ela terá em 2050.
      LEIA ano_atual
      LEIA ano_nascimento
      idade_atual = ano_atual − ano_nascimento
      idade_2050 = 2050 − ano_nascimento
      ESCREVA idade_atual

"""

#entrada
ano_atual = int(input('Digite o ano atual: '))
ano_nascimento = int(input('Digite o ano em que nasceu: '))
#processamento
idade_atual = ano_atual - ano_nascimento
idade_2050 = 2050 - ano_nascimento
#saída
print('A idade atual é: ', idade_atual)
print('A idade em 2050 sera: ', idade_2050)

"""#### 15. O custo ao consumidor de um carro novo é a soma do preço de fábrica com o percentual de lucro do distribuidor e dos impostos aplicados ao preço de fábrica. Faça um programa que receba o preço de fábrica de um veículo, o percentual de lucro do distribuidor e o percentual de impostos, calcule e mostre:
* o valor correspondente ao lucro do distribuidor;
* o valor correspondente aos impostos;
* o preço final do veículo.
        LEIA preco_fabrica
        LEIA percentual_lucro_distribuidr
        LEIA percentual_imposto
        lucro_distribuidor = preco_fabrica * percentual_lucro_distribuido / 100
        valor_imposto = preco_fabrica * percentual_imposto / 100
        preco_final = preco_fabrica + lucro_distribuidor + valor_imposto
        ESCREVA lucro_distribuidor
        ESCREVA valor_imposto
        ESCREVA preco_final

"""

#entrada
preco_fabrica = float(input('O preço de fábrica é: '))
percentual_lucro_distribuidor = float(input('O percentual de lucro do distribuidor é: '))
percentual_imposto = float(input('O percentual de imposto é: '))
#processamento
lucro_distribuidor = preco_fabrica * percentual_lucro_distribuidor / 100
valor_imposto = preco_fabrica * percentual_imposto / 100
preco_final = preco_fabrica + lucro_distribuidor + valor_imposto
#saída
print('O valor de lucro do distribuidor é: ', lucro_distribuidor)
print('Valor dos impostos é: ', valor_imposto)
print('O preço final do veículo é: ', preco_final)

"""### 16. Faça um programa que receba o número de horas trabalhadas e o valor do salário mínimo, calcule e mostre o salário a receber, seguindo estas regras:
* a hora trabalhada vale a metade do salário mínimo.
* o salário bruto equivale ao número de horas trabalhadas multiplicado pelo valor da hora trabalhada.
* o imposto equivale a 3% do salário bruto.
* o salário a receber equivale ao salário bruto menos o imposto.
      LEIA qtde_horas_trabalhadas
      LEIA valor_salario_minimo
      valor_hora_trabalhada = valor_salario_minimo / 2
      valor_salario_bruto = valor_hora_trabalhada * qtde_horas_trabalhadas
      imposto = valor_salario_bruto * 3 / 100
      Valor_salario_liquido =  valor_salario_bruto - imposto
      ESCREVA valor_salario_liquido
"""

#entrada
quantidade_horas_trabalhadas = float(input('A quantidade de horas trabalhadas é: '))
valor_salario_minimo = float(input('O valor do salário mínimo é: '))
#processamento
valor_hora_trabalhada = valor_salario_minimo / 2
valor_salario_bruto = valor_hora_trabalhada * quantidade_horas_trabalhadas
imposto = valor_salario_bruto * 3 / 100
valor_salario_liquido = valor_salario_bruto - imposto
#saída
print('O salário a receber é: ', valor_salario_liquido)

"""### 17. Um trabalhador recebeu seu salário e o depositou em sua conta bancária. Esse trabalhador emitiu dois cheques e agora deseja saber seu saldo atual. O banco criou uma taxa para a operação bancária de retirada que tem que pagar um imposto de 0.38% e o saldo inicial da conta está zerado.

      LEIA salario
      LEIA valor_cheque1
      LEIA valor_cheque2
      imposto_cheque1 = valor_cheque1 * 0.38 / 100
      saque1 = valor_cheque1 + imposto_cheque1
      imposto_cheque2 = cheque2 * 0.38 / 100
      saque2 = valor_cheque2 + imposto_cheque2
      saldo = salario - saque1 - saque2
      ESCREVA saldo

"""

#entrada
salario = float(input('O valor do salário é: '))
valor_cheque1 = float(input('O valor do primeiro cheque é '))
valor_cheque2 = float(input('O valor do segundo cheque é '))
#processamento
imposto_cheque1 = valor_cheque1 * 0.38 / 100
saque1 = valor_cheque1 + imposto_cheque1
imposto_cheque2 = valor_cheque2 * 0.38 / 100
saque2 = valor_cheque2 + imposto_cheque2
saldo = salario - saque1 - saque2
#saída
print('O saldo final é: ', saldo)

"""### 18. Pedro comprou um saco de ração com peso em quilos. Ele possui dois gatos, para os quais fornece a quantidade de ração em gramas. A quantidade diária de ração fornecida para cada gato é sempre a mesma. Faça um programa que receba o peso do saco de ração em gramas e a quantidade de ração fornecida para cada gato, calcule e mostre quanto restará de ração no saco após cinco dias.

      LEIA peso_saco
      LEIA racao_gato1
      LEIA racao_gato2
      total_final = peso_saco − 5 * (racao_gato1 + racao_gato2)
      ESCREVA total_final
"""

#entrada
peso_saco = float(input('Digite o peso do saco de ração: '))
racao_gato1 = float(input('Digite a quantidade de ração fornecida ao gato 1: '))
racao_gato2 = float(input('Digite a quantidade de ração fornecida ao gato 2: '))
#processamento
total_final = peso_saco - 5 * (racao_gato1 + racao_gato2)
#saída
print('A quantidade de ração que restará após 5 dias é: ', total_final)

"""### 19. Cada degrau de uma escada tem X de altura. Faça um programa que receba essa altura e a altura que o usuário deseja alcançar subindo a escada, calcule e mostre quantos degraus ele deverá subir para atingir seu objetivo, sem se preocupar com a altura do usuário. Todas as medidas fornecidas devem estar em metros.
      LEIA altura_degrau
      LEIA altura_desejada
      quantidade_de_degraus = altura_desejada // altura_degrau
      ESCREVA quantidade_de_degraus
**Observação**: o operador **//** em Python é utilizado para pegar a parte inteira de uma divisão
"""

#entrada
altura_degrau = float(input('Altura do degrau: '))
altura_desejada = float(input('Altura que se deseja alcançar: '))
#processamento
quantidade_de_degraus = altura_desejada // altura_degrau
#saída
print('A quantidade de degraus que devera subir é: ', quantidade_de_degraus)

"""### 20. Faça um programa que receba a medida do ângulo (em graus) formado por uma escada apoiada no chão e encostada na parede e a altura da parede onde está a ponta da escada. Calcule e mostre a medida dessa escada. Observação: as funções trigonométricas implementadas nas linguagens de programação trabalham com medidas de ângulos em radianos.
      LEIA angulo
      LEIA altura
      import math # carrega a biblioteca matemática
      radiano = angulo * math.pi / 180
      escada = altura / math.sin(radiano)
      ESCREVA escada
**Observação**: Para usar seno em Python, deve-se usar esta linha de código **import math** e esta, no cálculo, **math.sin(numero)**

**import math**

escada = altura / **math.sin**(numero)
"""

#entrada
angulo = float(input('Digite o valor do angulo: '))
altura = float(input('Digite o valor da altura: '))
#processamento
import math
radiano = angulo * math.pi / 180
escada = altura / math.sin(radiano)
#saída
print('As medidas da escada são: ', escada)

"""### 21. Uma pessoa deseja pregar um quadro em uma parede. Faça um programa para calcular e mostrar a que distância a escada deve estar da parede. A pessoa deve fornecer o tamanho da escada e a altura em que deseja pregar o quadro. Lembre-se de que o tamanho da escada deve ser maior que a altura que se deseja alcançar.
      LEIA Z
      LEIA X
      Y = Z ** 2 - X ** 2
      Y = Y **1/2
      ESCREVA Y

"""

#entrada
tamanho_escada = float(input('Digite o tamanho da escada: '))
altura_pregar = float(input('Digite a altura em que se pregara o quadro: '))
#processamento
y = tamanho_escada ** 2 - altura_pregar ** 2
y = y ** (1/2)
#saída
print('A distância que a escada tem que estar da parede é: ', y)

"""###22. Sabe-se que o quilowatt de energia custa um quinto do salário mínimo. Faça um programa que receba o valor do salário mínimo e a quantidade de quilowatts consumida por uma residência. Calcule e mostre:


* o valor de cada quilowatt;
* o valor a ser pago por essa residência;
* o valor a ser pago com desconto de 15%.
      LEIA valor_salario
      LEIA qtde_quilowatt
      valor_quilowatt = valor_salario / 5
      valor_em_reais = valor_quilowatt * qtde_quilowatt
      valor_descontado = valor_em_reais * 15 / 100
      valor_com_desconto =  valor_em_reais − valor_descontado
      ESCREVA valor_quilowatt
      ESCREVA valor_em_reais
      ESCREVA valor_com_desconto

"""

#entrada
valor_salario = float(input('Digite o valor do salário: '))
quantidade_quilowatt = float(input('Digite a quantidade de quilowatts: '))
#processamento
valor_quilowatt = valor_salario / 5
valor_em_reais = valor_quilowatt * quantidade_quilowatt
valor_descontado = valor_em_reais * 15 / 100
valor_com_desconto = valor_em_reais - valor_descontado
#saída
print('O valor de cada quilowatt é: ', valor_quilowatt)
print('O valor em reais é: ', valor_em_reais)
print('O valor com desconto é: ', valor_com_desconto)

"""### 23. Faça um programa que receba um número real, encontre e mostre:

* a parte inteira desse número;
* a parte fracionária desse número;
* o arredondamento desse número.

      LEIA numero
      parte_inteira = numero // 1
      parte_fracionaria = numero - parte_inteira
      numero_arredondado = arredonda (numero)
      ESCREVA parte_inteira
      ESCREVA parte_fracionaria
      ESCREVA numero_arredondado
      
**Observação**: Para arredondar um número em Python, usa-se a função **round(numero)**, onde se o número real/float estiver em igual distância entre o inteiro de cima e o inteiro de baixo, esta função arredonda para o número par mais próximo.


"""

#entrada
numero = float(input('Digite um número: '))
#processamento
parte_inteira = numero // 1
parte_fracionaria = numero - parte_inteira
numero_arredondado = round(numero)
#saída
print('A parte inteira é: ', parte_inteira)
print('A parte fracionada é: ', parte_fracionaria)
print('O número arredondado é: ', numero_arredondado)

"""### 24. Faça um programa que receba uma hora formada por hora e minutos (um número real), calcule e mostre a hora digitada apenas em minutos. Lembre-se de que:
* para quatro e meia, deve-se digitar 4.30;
* os minutos vão de 0 a 59.
      LEIA hora
      h = pegar a parte inteira da variável hora
      minutos = hora − h
      conversao = (h * 60) + (minutos * 100)
      ESCREVA conversao

"""

# h = hora // 1 
#entrada
hora = float(input('Digite a hora: '))
#processamento
h = hora // 1
minutos = hora - h
conversao = (h * 60) + (minutos * 100)
#saída
print('A hora convertida em minutos é: ', conversao)

"""### 25. Faça um programa que receba o custo de um espetáculo teatral e o preço do convite desse espetáculo. Esse programa deverá calcular e mostrar a quantidade de convites que devem ser vendidos para que, pelo menos, o custo do espetáculo seja alcançado.

      LEIA custo
      LEIA convite
      quantidade = custo / convite
      ESCREVA quantidade

"""

#entrada
custo = float(input('O custo do espetáculo é: '))
convite = float(input('O preço do convite é: '))
#processamento
quantidade = custo / convite
#saída
print(' A quantidade de convites que precisam ser vendidos é: ', quantidade)