# -*- coding: utf-8 -*-
"""Ellen Dayane Vivas Rosa Mezaki - 211_Est_Rep_SemContador_n.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iOhRn1ybwKDxMeP2J5XKzUIM7UEv2fgS

### **EXERCÍCIOS DE ESTRUTURA DE REPETIÇÃO SEM CONTADOR**

###1. Construir um algoritmo para calcular e apresentar o total de salários pagos de uma, mas não é informado a quantidade de pessoas, então use como critério de parada (condição da estrutura de repetição, digitar zero no salário para sair.
"""

# não pode usar for porque é estrutura de repetição sem contador 
salario = float(input('Informe o salário: '))
total = 0
while salario > 0:
    total = total + salario
    salario = float(input('Informe um salário: '))
print('O total de salários pagos é:', total)

"""###2. Construir um algoritmo para calcular e apresentar a idade atual de algumas pessoas em relação ao ano atual, mas não é informado a quantidade de pessoas, então use como critério de parada (condição da estrutura de repetição, digitar zero no ano de nascimento para sair."""

ano_nascimento = int(input('Informe o ano de nascimento: '))
idade = 0
while ano_nascimento > 0:
    ano_atual = int(input('Informe o ano atual: '))
    idade = ano_atual - ano_nascimento
    print('A idade atual é:', idade)
    ano_nascimento = int(input('Informe o ano de nascimento: '))

"""###3. Faça um programa que receba a idade e a altura de várias pessoas. Calcule e exiba a média das alturas das pessoas com mais de 20 anos. Para encerrar a entrada de dados, digite uma idade negativa ou igual a zero.



"""

idade = int(input('informe a idade: '))
soma_alturas = 0
contador = 0
while idade > 0:
    if idade > 20:
        altura = float(input('Informe a altura: '))
        soma_alturas = soma_alturas + altura
        contador = contador + 1
    idade = int(input('Informe a idade: '))
media = soma_alturas / contador
print('A média de alturas com mais de 20 anos é', media)

"""###4. Faça um programa que receba um conjunto de valores inteiros, calcule e exiba o maior e o menor valor do conjunto.


*   Para encerrar a entrada de dados, deve ser digitado o valor zero;
*   Para valores negativos, deve ser enviada uma mensagem;
*   Esses valores (zero e negativos) não entrarão nos cálculos.


"""

valor_inteiro = int(input('Informe um número inteiro: '))
maior = valor_inteiro
menor = valor_inteiro
while valor_inteiro != 0:
    if valor_inteiro > maior:
        maior = valor_inteiro
    elif valor_inteiro <= menor and valor_inteiro > 0: 
        menor = valor_inteiro
    if valor_inteiro < 0:
        print('valor inválido')
    valor_inteiro = int(input('Informe um número inteiro: '))  
print('O maior número é: ',maior, 'e o menor número é: ',menor)

"""###5. No final do ano muitas pessoas compram presentes. Faça um programa que registre alguns dados das pessoas, usando como critério de parada a letra ‘n’, para a pergunta “Deseja cadastrar outro (‘s’/’n’)?”, para identificar o perfil dos compradores numa loja de roupas e apresente como resultado a:
*   Quantidade de mulheres e de homens;
*   Quantidade de mulheres e de homens abaixo e acima de 18 anos.
"""

cadastro = str(input('Deseja cadastrar um cliente(s ou n)? '))
quantidade_mulheres = 0
quantidade_homens = 0
idade = 0
maior_idade = 0
menor_idade = 0
while cadastro != 'n':
    pessoa = str(input('Informe o sexo da pessoa(f ou m): '))
    if pessoa == 'f':
        print('Mulher')
        quantidade_mulheres = quantidade_mulheres + 1   
    elif pessoa == 'm':
        print('Homem') 
        quantidade_homens = quantidade_homens + 1
    idade = int(input('Informe a idade: '))
    if idade >= 18:
        print('Maior de idade')
        maior_idade = maior_idade + 1
    elif idade < 18:
        print('Menor de idade')
        menor_idade = menor_idade + 1   
    cadastro = str(input('Deseja cadastrar outro(s ou n)? '))
print('A quantidade de mulheres é: ',quantidade_mulheres, 'e a quantidade de homens é: ',quantidade_homens)
print('A quantidade de mulheres e homens abaixo de 18 anos é: ', menor_idade, 'e a quantidade de mulheres e homens acima de 18 anos é: ', maior_idade)

"""###6. Faça um programa para o curso de ADS (6 módulos) que calcule e apresente os seguintes itens:
*  Quantidade de homens e mulheres de cada módulo;
*  Média de idades de cada módulo;
*  Quantidade de homens e mulheres do curso todo;
*  Média de idades do curso todo.
"""

total_homens = 0 #arrumar
total_mulheres = 0
idade = 0
soma = 0
contador = 's' or 'S'
for i in range (1,7):
    homem = 0
    mulher = 0
    soma_idade = 0
    contador = input('Deseja informar um aluno? "s" ou "n"?')
    print('modulo%i'%i)
    while contador != 'n':
        sexo = str(input('Informe se o sexo é feminino (f) ou masculino (m): '))
        idade = int(input('Informe a idade: '))
        if sexo == 'f':
            mulher = mulher + 1
            total_mulheres += mulher
        if sexo == 'm':
            homem = homem + 1
            total_homens += homem
        soma_idade = soma_idade + idade
        soma = soma + idade
        contador = input('Deseja continuar? "s" ou "n"?')
    media_modulo = soma_idade / (homem + mulher) 
    print('Quantidade de alunos do módulo: ',(homem + mulher))
    print('Quantidade de homens do módulo: ',homem,'. Quantidade de mulheres do módulo: ',mulher)
    print(f'Média das idades do módulo: {media_modulo:.2f}')
    media = soma / (total_homens + total_mulheres)
print('Quantidade de alunos do curso: ', (total_homens + total_mulheres))
print(f'Média das idades do curso: {media:.2f}')