# -*- coding: utf-8 -*-
"""Ellen Dayane Vivas Rosa Mezaki - 211_Matriz_n.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WMhvQ9wDCfQEvQ3hN-2lodSQYKc4kRrQ

### 1. Faça um programa que leia uma matriz 2x3 (2 linhas, 3 colunas). Apresenta os elementos da matriz e seus respectivos índices.
"""

matriz = [] # ................................................... Lendo a matriz
for lin in range(2): # lin corresponde ao índice das linhas

    vet_linha = []

    for col in range(3): # col coresponde ao índice das colunas
        vet_linha.append(int(input('Digite o valor ['+ str(lin) + '][' + str(col) + ']: ')))
        
    matriz.append(vet_linha)

for lin in range(2):  # .................................. Apresentando a matriz
    for col in range(3): 
        print(matriz[lin][col], end='\t')
    print()

for lin in range(len(matriz)):  # a função len(matriz), possui a quantidade de linhas
    for col in range(len(matriz[0])): # a função len(matriz[0]), possui a quantidade de colunas
        print('O elemento ',matriz[lin][col], ' está na linha',lin,' e na coluna',col)

"""### 2. Faça um programa que carregue uma matriz 2 x 2, que representa o salário de 4 funcionários, calcule e mostre a soma total de todos os elementos que será o montante pago pela empresa a esses funcionários."""

soma = []
cont_soma = 0
for linha in range(2):
    vet_linha = []
    for coluna in range(2):
        vet_linha.append(float(input('Informe o salário ['+ str(linha) + '][' + str(coluna) + ']: ')))
    soma.append(vet_linha)   
for linha in range(2):  
    for coluna in range(2):
        cont_soma += soma[linha][coluna]
print(f'O montante pago pela empresa aos funcionários é: R$ {cont_soma:.2f}')

"""### 3. Faça um programa que carregue uma matriz 3 x 2, que representa preços de produtos, crie OUTRA matriz que armazene todos os preços com 7% de aumento."""

matriz = []
preco_final = []
for linha in range(3):
    preco = []
    for coluna in range(2):
        preco.append(float(input('Informe o preço do produto ['+ str(linha) + '][' + str(coluna) + ']: ')))
    matriz.append(preco)   

for linha in range(3):
    preco = []  
    for coluna in range(2):
        preco.append(float(matriz[linha][coluna] * (7 / 100) + matriz[linha][coluna]))
    preco_final.append(preco)
    
for linha in range(3): 
    for coluna in range(2):
        print('O valor inicial do produto é: R$', matriz[linha][coluna])
        print('O valor com ajuste de 7% fica: R$', preco_final[linha][coluna])

"""### 4. Faça um programa para armazenar em uma matriz 5x2 preços. Encontre e apresente os ÍNDICES dos valores menores que 23 reais."""

matriz = [] 
for lin in range(5): 
    preco = []
    for col in range(2):
        preco.append(float(input('Digite o preço ['+ str(lin) + '][' + str(col) + ']: ')))   
    matriz.append(preco)
for lin in range(5):
    for col in range(2): 
        if matriz[lin][col] < 23:
            print('O produto que possui o preço menor que R$23,00 esta na linha',{lin},' e na coluna',{col})

"""### 5. Faça um programa que leia números inteiros m e n e os elementos de uma matriz A de números inteiros de dimensão m x n e conte o número de elementos que são iguais a zero.

"""

m = int(input('Digite a dimensão m da matriz:'))
n = int(input('Digite a dimensão n da matriz:'))
matriz = []
soma = 0
for lin in range(m): 
    numero = []
    for col in range(n):
        numero.append(int(input('Informe o número ['+ str(lin) + '][' + str(col) + ']: ')))   
    matriz.append(numero)
for lin in range(m):
    for col in range(n): 
        if matriz[lin][col] == 0:
            soma = soma + 1
print('O número de elementos que são iguais a 0 são: ',soma)

"""### 6. Faça um programa que carregue: *um vetor com oito posições com os nomes das lojas; * um outro vetor com quatro posições com os nomes dos produtos; * uma matriz com os preços de todos os produtos em cada loja. O programa deve mostrar todas as relações (nome do produto – nome da loja) nas quais o preço não ultrapasse R$ 120,00. Escolha qual é o tipo da função que quer.

"""

preco = []
produto = []
loja = []
for i in range(8):
    loja.append(input('Informe a loja: '))

for i in range(4):
    produto.append(input('Informe o produto: '))

for linha in range(8):
    vetor_linha = []
    for coluna in range(4):
        vetor_linha.append(float(input('Informe o preço do produto ' + produto[coluna] + ' da loja ' + loja[linha] + ' ')))
    preco.append(vetor_linha)        

for linha in range(8):
    for coluna in range(4):
        if preco[linha][coluna] < 120:
            print('O produto ', produto[coluna], ' de preço ', preco[linha][coluna], ' da loja ', loja[linha], ' , custa menos que R$ 120,00')