# -*- coding: utf-8 -*-
"""Ellen Dayane Vivas Rosa Mezaki - 211_Est_Repeticao_n.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kmwevYk4LnjwVO_wA5LgU9hCJfKiYKRh

#ESTRUTURA DE REPETIÇÃO
Todos estes algoritmos/programas podem ser implementados com o comando **while** ou **for**

###1. Faça um algoritmo  que mostre 10 vezes a frase “Bem vindo a Fatec!”. Pode implementar com o comando while ou for.
"""

print('Exemplo com o while')
qalunos = 1 # inicialização
while qalunos <= 10: # condição
    print(qalunos, "Bem vindo a Fatec")
    qalunos = qalunos + 1 #incremento

print('\nExemplo com o for')
for contador in range(1,11):
    print(contador, "Bem vindo a Fatec")

"""###2. Faça um algoritmo que mostre o cumprimento ‘Olá ‘ para o nome de alguém (4 pessoas). Exemplo ‘Olá Mariana’. Pode implementar com o comando while ou for.
 
"""

alunos = 1
while alunos <= 4:
   nome = input("Informe um nome: ")
   print(alunos,"Olá", nome) 
   alunos = alunos + 1



"""###3. Faça um algoritmo que mostre os valores de 0 a 15. Pode implementar com o comando while ou for.

"""

for contador in range (16):
    print(contador)

"""###4. Faça um algoritmo que mostre os valores de 3 a 20. Pode implementar com o comando while ou for.

"""

valor = 3
while valor <= 20:
    print(valor)
    valor = valor + 1

"""###5. Faça um algoritmo que calcule e mostre a tabuada do 5. Pode implementar com o comando while ou for.

"""

for contador in range (1,11):
    tabuada = contador * 5
    print(tabuada)

"""###6. Faça um algoritmo que receba a idade de 10 pessoas, calcule e exiba a quantidade de pessoas maiores de idade, sendo que a maioridade é obtida após completar 18 anos. Pode implementar com o comando while ou for.

"""

maior_idade = 0
menor_idade = 0
for contador in range (10):
    idade = int(input('Informe a idade: '))
    if idade >= 18:
        maior_idade = maior_idade + 1
    else:
        menor_idade = menor_idade + 1
print('A quantidade de pessoas maiores de idade é: ',maior_idade)

"""###7. Escreva um algoritmo que receba 23 números, calcule e exiba a quantidade de números pares e impares. Pode implementar com o comando while ou for.

"""

contador = 0
cont_par = 0
cont_impar = 0
while contador < 23:
    numero = int(input('Informe o valor: '))
    if numero % 2 == 0:
        cont_par = cont_par + 1
    else:
        cont_impar += 1 
    contador = contador + 1
print('Quantidade de valores pares:',cont_par,'Quantidade de valores ímpares:',cont_impar)

"""###8. Faça um algoritmo que calcule e exiba o salário reajustado de dez funcionários de acordo com a seguinte regra (pode implementar com o comando while ou for): 
Salário até 300, reajuste de 50%; 

Salários maiores que 300, reajuste de 30%.



"""

qtde_funcionarios = 1 # inicialização
while qtde_funcionarios <= 10: # condição
    salario = float(input('Informe o salário '))
    if salario <= 300:
        novo = salario + (salario * 50 / 100)
    else:
        novo = salario + (salario * 30 / 100)
    print('O novo salário é',novo)
    qtde_funcionarios = qtde_funcionarios + 1 # incremento

"""###9. Faça um algoritmo que conheça 4 valores diferentes, some-os e mostre o resultado. Pode implementar com o comando while ou for.

"""

soma = 0
for valor in range (0,4):
    numero = int(input('Informe um numero: '))
    soma += numero
print('A soma dos quatro valores é: ', soma)

"""###10. Elabore um algoritmo que calcule e informe a média de idades de 5 alunos.Pode implementar com o comando while ou for."""

contador = 0
soma = 0 
while contador < 5:
    idade = int(input('Informe a idade: '))
    soma = soma + idade
    contador = contador + 1
media = soma / 5
print('A média das idades é: ', media)

"""###11. Construir um algoritmo para calcular a média aritmética de preços de 5 produtos. Pode implementar com o comando while ou for.

"""

soma = 0
for contador in range (5):
    preco = float(input('Informe o preço do produto: '))
    soma = soma + preco
media = soma / 5
print(F'A média dos preços dos produtos é: {media:.2f}')

"""###12. Construir um algoritmo que, dado o valor de 20 preços de TV, determine e apresente o valor mais caro e mais barato entre eles. Pode implementar com o comando while ou for.

"""

contador = 0
for contador in range (20):
    preco = float(input('Informe o preço da TV: '))
    if contador == 0:
        maior_preco = preco
        menor_preco = preco
        contador = contador + 1
    if preco > maior_preco:
        maior_preco = preco
        contador = contador + 1
    if preco < menor_preco:
        menor_preco = preco
        contador = contador + 1
print('O maior preço é: ', maior_preco)
print('O menor preço é: ', menor_preco)

"""###13. Faça um algoritmo que leia de dez alunos altura e nome.  Mostre o aluno mais alto e mais baixo e seus respectivos nomes. Pode implementar com o comando while ou for.

"""



contador = 0 #corrigir
for contador in range (10):
    nome = str(input('Informe o nome do aluno: '))
    altura = float(input('Informe a altura do aluno: '))
    if contador == 0:
        alto = altura
        baixo = altura
        nome_alto = nome
        nome_baixo = nome
    if altura >= alto:
        alto = altura
        nome_alto = nome
    if altura <= baixo:
        baixo = altura
        nome_baixo = nome
    contador = contador + 1
print('Nome do aluno alto: ', nome_alto, 'com altura:', alto)
print('Nome do aluno baixo: ', nome_baixo, 'com altura:', baixo)

"""###14. Faça um programa que informada a idade de 10 nadadores o mesmo terá condições de classificar em uma das seguintes categorias: infantil = 5 - 10 anos; juvenil = 11-17 anos; adulto >= maiores de 18 anos.

"""

idade = 0
for contador in range (10):
    idade = int(input('Informe a idade: '))
    if idade >= 5 and idade <= 10:
        print('A categoria é infantil')
    if idade >= 11 and idade <= 17:
        print('A categoria é juvenil')
    if idade >= 18:
        print('A categoria é adulto')

"""### 15. Faça um programa que receba duas notas de seis alunos. Esta tabela não representa o cálculo efetuado pela faculdade. Pode implementar com o comando while ou for. Calcule e mostre:

* a média aritmética das duas notas de cada aluno; e
* a mensagem que está na tabela a seguir:


Média aritimética | Mesagem
---|---
Até 3|Reprovado
Entre 3 e 7 |Exame
De 7 para cima| Aprovado

* o total de alunos aprovados;
* o total de alunos de exame;
* o total de alunos reprovados;
* a média da classe.
"""

contador_reprovado = 0
contador_exame = 0
contador_aprovado = 0
media_sala = 0
for contador in range (1,7):
    primeira_nota = float(input('Digite a primeira nota do aluno: '))
    segunda_nota = float(input('Digite a segunda nota do aluno: '))
    media = (primeira_nota + segunda_nota) / 2
    if media <= 3:
        print('reprovado')
        contador_reprovado = contador_reprovado + 1
    if media > 3 and media < 7:
        print('exame')
        contador_exame = contador_exame + 1
    if media >= 7:
        print('aprovado')
        contador_aprovado = contador_aprovado + 1
    print('A média do aluno é: ', media)
    media_sala = media_sala + media
print('O número de alunos aprovados é: ', contador_aprovado)
print('O número de alunos que estão de exame é: ', contador_exame)
print('O número de alunos reprovados é: ', contador_reprovado)
print('A média da sala é: ', media_sala / 6)

"""### 16. Um funcionário de uma empresa recebe, anualmente, aumento salarial. Pode implementar com o comando while ou for.

**Sabe-se que:**

* Esse funcionário foi contratado em 2005, com salário inicial de R$ 1.000,00.
* Em 2006, ele recebeu aumento de 1,5% sobre seu salário inicial.
* A partir de 2007, os aumentos salariais sempre corresponderam ao dobro do percentual do ano anterior.

**Faça um programa que determine o salário atual desse funcionário.**

```
salario_inicial =1000
percentual_aumento_ano  = 1.5 / 100
aumento_ano = salario_inicial * percentual_aumento_ano
salario_ano = salario_inicial + aumento_ano

PARA ano NO INTERVALO DE 2007 ATÉ ano_atual + 1
    percentual_aumento_ano = percentual_aumento_ano * 2
    aumento_ano = salario_ano * percentual_aumento_ano
    salario_ano = salario_ano + aumento_ano
    
ESCREVA ano, salario_do_ano
```

"""

# Digite seu código aqui

"""###  17. Foi feita uma pesquisa com as crianças de uma determinada localidade. Faça um programa que:

* leia o número de crianças nascidas no período;
* identifique o sexo (M ou F) e a idade da criança em meses.

**O programa deve calcular e mostrar:**

* a percentagem de crianças do sexo marculino;
* a percentagem de crianças do sexo feminino;
* a percentagem de crianças menores que 24 meses.

**Observação:

porcentagem_de_meninos = total_de_meninos / total_de_criancas_nascidas * 100

porcentagem_de_meninas = total_de_meninas / total_de_criancas_nascidas * 100
porcentagem_de_criancas_menores_de_24_mese=criancas_menores_de_24_meses/total_de_criancas_nascidas*100
"""

# Digite seu código aqui

"""### 18. Foi feita uma estatística em cinco cidades brasileiras para coletar dados sobre acidentes de trânsito. Pode implementar com o comando while ou for. Foram obtidos/lidos os seguintes dados:

* nome da cidade;
* número de veículos de passeio;
* número de acidentes de trânsito com vítimas.

**Deseja-se saber:**

* o maior índice de acidentes de trânsito e a qual cidade pertence;
* o menor índice de acidentes de trânsito e a qual cidade pertence;
* qual é a média de veículos nas cinco cidades juntas;
* qual é a média de acidentes de trânsito nas cidades com mais de 2.000 veículos de passeio.

#### ALGORITMO
---

```
total_cidades_pesquisadas = 5
somatoria_veiculos_cidades = 0
somatoria_acidentes_cidades_mais_2000_veiculos = 0
numero_cidades_mais_2000_veiculos = 0

PARA cidade NO INTERVALO total_cidades_pesquisadas
    LEIA nome_cidade, numero_veiculos, numero_acidentes
    SE cidade == 0
        maior_casos_acidentes = numero_acidentes
        cidade_maior_casos_acidentes = nome_da_cidade
        menor_casos_acidentes = numero_acidentes
        cidade_menor_casos_acidentes = nome_cidade
    SENÃO
        SE numero_acidentes > maior_casos_acidentes
             maior_casos_acidentes = numero_acidentes
             cidade_maior_casos_acidentes = nome_cidade
        SE numero_de_acidentes < menor_casos_acidentes
            menor_caso_acidentes = numero_acidentes
            cidade_menor_casos_acidentes = nome_cidade
                
    somatoria_veiculos_cidades += numero_veiculos
    
    SE numero_veiculos > 2000
        soma_acidentes_acima_2000_veiculos += numero_acidentes
        numero_cidades_mais_2000_veiculos += 1
        
media_carros_cidades = somatoria_veiculos_cidades / total_cidades_pesquisadas

SE numero_cidades_mais_2000_veiculos == 0
    ESCREVA “Não foi informada nenhuma cidade com mais de 2000 veículos”
SENAO
    media_acidentes_cidade_mais_2000_veiculos = soma_acidentes_acima_2000_veiculos /                        numero_cidades_mais_2000_veiculos
    
    ESCREVA cidade_maior_casos_acidentes,cidade_maior_casos_acidentes
    ESCREVA cidade_menor_casos_acidentes, menor_casos_acidentes 
    ESCREVA media_carros_cidades
    ESCREVA media_acidentes_cidade_mais_2000_veiculos
```

"""

# Digite seu código aqui

"""### 19. Faça um programa que monte os oito primeiros termos da sequência de Fibonacci. Pode implementar com o comando while ou for.

#### ALGORITMO
___
```
numero_elementos_sequencia = 8
elementoN = 0
elementoNmais1 = 1

ESCREVA elementoN
ESCREVA elementoNmais1

PARA elemento NO INTERVALO DE 3 ATÉ numero_elementos_sequencia
    valor_fibonacci_atual = elementoN + elementoNmais1
   
    ESCREVA valor_fibonacci_atual
    
    elementoN = elementoNmais1
    elementoNmais1 = valor_fibonacci_atual
    
```
0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, …
"""

# Digite seu código aqui

"""### 20. Em uma fábrica trabalham homens e mulheres divididos em três classes:

* trabalhadores que fazem até 30 peças por mês — classe 1;
* trabalhadores que fazem de 31 a 50 peças por mês — classe 2;
* trabalhadores que fazem mais de 50 peças por mês — classe 3.

**Os salários são compostos da sequinte maneira:**

* A classe 1 recebe salário mínimo.
* A classe 2 recebe salário mínimo mais 3% deste salário por peça, acima das 30 peças iniciais.
* A classe 3 recebe salário mínimo mais 5% desse salário por peça, acima das 30 peças iniciais.

Pode implementar com o comando while ou for.

**Faça um programa que receba:**

* o número do operário,
* o número de peças fabricadas no mês,
* o sexo do operário,

**Calcule e mostre:**

* o número do operário e seu salário;
* o total da folha de pagamento da fábrica;
* o número total de peças fabricadas no mês;
* a média de peças fabricadas pelos homens;
* a média de peças fabricadas pelas mulheres; e
* o número do operário ou operária de maior salário.

**A fábrica possui 15 operários.**

#### ALGORITMO
---
```
total_de_operarios = 15
valor_do_salario_minimo = 954

total_da_folha_de_pagamento_no_mes = 0
total_de_pecas_fabricadas_no_mes = 0

media_das_pecas_fabricadas_por_homens = 0
media_das_pecas_fabricadas_por_mulheres = 0

total_de_homens = 0
total_de_mulheres = 0

meta_minima = 30
meta_classe3 = 50

porcentagem_de_bonus_da_classe1 = 0
porcentagem_de_bonus_da_classe2 = 2 / 100
porcentagem_de_bonus_da_classe3 = 3 / 100

total_de_operarios_homens = 0
total_de_operarios_mulheres = 0

somatorio_das_pecas_fabricadas_por_homens = 0
somatorio_das_pecas_fabricadas_por_mulheres = 0

maior_salario_entre_os_operarios = -1

PARA operario NO INTERVALO de total_de_operarios
    ESCREVA “Digite o número do operário “
    LEIA numero_do_operario
    
    ESCREVA “Digite o sexo do operário (M ou F) “
    LEIA sexo_do_operario
    
    ESCREVA “Digite o total de peças fabricadas pelo operario“
    LEIA total_de_pecas_fabricadas_pelo_operario
    
    SE total_de_pecas_fabricadas_pelo_operario <= meta_minima
        porcentagem_da_classe_do_operario = porcentagem_de_bonus_da_classe1
    SENAO SE total_de_pecas_do_operario >= meta_classe3
        porcentagem_da_classe_do_operario = porcentagem_de_bonus_da_classe3
    SENAO
          porcentagem_da_classe_do_operario = porcentagem_de_bonus_da_classe2
          
    SE total_de_pecas_fabricadas_pelo_operario > meta_minima
        producao_acima_da_meta = total_de_pecas_fabricadas_pelo_operario - meta_minima
    SENAO
        producao_acima_da_meta = 0
    
    bonus_de_producao = valor_do_salario_minimo * porcentagem_da_classe_do_operario * producao_acima_da_meta
    
    salario_do_operario = valor_do_salario_minimo + bonus_de_producao
    
    ESCREVA numero_do_operario, salario_do_operario
    
    total_da_folha_de_pagamento_no_mes += salario_do_operario 
    total_de_pecas_fabricadas_no_mes += total_de_pecas_fabricadas_pelo_operario
    
    SE sexo_do_operario ESTA EM "Hh"
        total_de_homens += 1
        somatorio_das_pecas_fabricadas_por_homens += total_de_pecas_fabricadas_pelo_operario
        
    SE sexo_do_operario ESTA EM "Mm"
        total_de_mulheres += 1
        somatorio_das_pecas_fabricadas_por_mulheres += total_de_pecas_fabricadas_pelo_operario
        
    SE salario_do_operario > maior_salario_entre_os_operarios
        numero_do_operario_com_o_maior_salario = numero_do_operario
        maior_salario_entre_os_operarios = salario_do_operario
        
media_das_pecas_fabricadas_por_homens = somatorio_das_pecas_fabricadas_por_homens / total_de_homens

media_das_pecas_fabricada_por_mulheres = somatorio_das_pecas_fabricadas_por_mulheres / total_de_mulheres

ESCREVA total_da_folha_de_pagamento_no_mes
ESCREVA total_de_pecas_fabricadas_no_mes
ESCREVA media_das_pecas_fabricada_por_homens
ESCREVA media_das_pecas_fabricada_por_mulheres
ESCREVA numero_do_operario_com_o_maior_salario
```
"""

# Digite seu código aqui

"""### 21.  Faça um programa que receba o valor de uma dívida e mostre uma tabela com os seguintes dados:

* valor da dívida,
* valor dos juros, 
* quantidade de parcelas
* valor da parcela.

**Os juros e a quantidade de parcelas seguem a tabela:** 

Quantidade de parcelas |  % de juros sobre o valor inicial da dívida
---|---
1 |0
3 |10
6 |15
9 |20
12 |25

**Exemplo de saída do programa:**

Valor da dívida|Valor dos juros (em reais) | Quantidade de parcelas| Valor da parcela
---|---|---|---
1000,00 |0| 1| 1.000,00
1100,00 |100 |3| 366,67
1150,00 |150 |6| 191,67
1200,00 |200 |9| 133,33
1250,00 |250 |12|104,16

"""

# Digite seu código aqui

"""### 22. Faça um programa que receba:

* o preço unitário,
* a refrigeração (S para os produtos que necessitem de refrigeração e N para os que não necessitem)
* a categoria (A — alimentação; L — limpeza; e V — vestuário)

**Calcule e mostre:**

* O custo de estocagem, calculado de acordo com a tabela a seguir.


Preço unitário| Refrigeração| Categoria| Custo de estocagem
---|---|---|---
Até 20 | - |  A| 2,00
Até 20|-  |L  |3,00
Até 20| - |  V|4,00
----------------------|----------------------|----------------------|----------------------
Entre 20 e 50 (inclusive)|S  | - |6,00
Entre 20 e 50 (inclusive)|  N|  -| 0,00 |
----------------------|----------------------|----------------------|----------------------
Maior que 50| S| A |  5,00|
Maior que 50| S | L |  2,00| 
Maior que 50| S| V |  4,00| 
Maior que 50|  N|A ou V  |0,00  | 
Maior que 50|  N| L | 1,00 | 


* O imposto calculado de acordo com as regras a seguir:
  * Se o produto possuir **categoria A** e **refrigeração S**, seu imposto será de 2% sobre o preço
unitário; caso contrário, será de 4%.
  * O preço final, ou seja, preço unitário mais custo de estocagem mais imposto.
  * A classificação calculada usando a tabela a seguir.

Preço final| Classificação
---|---
Até 20,00 |Barato
Entre 20,00 e  100,00 (inclusive)|Normal
Acima de R$ 100,00| Caro

* A média dos valores adicionais, ou seja, a média dos custos de estocagem e dos impostos dos doze produtos.
* O maior preço final.
* O menor preço final.
* O total dos impostos.
* A quantidade e a classificação de produtos com classificação barato.
* A quantidade e a classificação de produtos com classificação caro.
* A quantidade e a classificação de produtos com classificação normal.

####ALGORITMO
---

```
total_de_produtos = 12

total_de_produtos_baratos = 0
total_de_produtos_normais = 0
total_de_produtos_caros = 0

total_de_custos_adicionais = 0

PARA produto NO INTERVALO DE total_de_produtos
    LEIA preco_do_produto, produto_necessita_de_refrigeracao, categoria_do_produto
    
    SE preco_do_produto <= 20
        SE categoria_do_produto == "A"
            custo_de_estocagem = 2
        SE categoria_do_produto == "L"
            custo_de_estocagem = 3
        SE categoria_do_produto == "V"
            custo_de_estocagem = 4
           
    SE  prodo_do_produto > 20 E preco_do_produto <= 50
        SE produto_necessita_de_refrigeracao == "S"
            custo_de_estocagem = 6
        SENAO
            custo_de_estocagem = 0
            
    SE preco_do_produto > 50
        SE produto_necessita_de_refrigeracao == "S"
            SE categoria_do_produto == "A"
                custo_de_estocagem = 5
            SE categoria_do_produto == "L"
                custo_de_estocagem = 2
            SE categoria_do_produto == "V"
                custo_de_estocagem = 4
        SENAO
            SE categoria_do_produto = "A" OU categoria_do_produto = "V"
                custo_de_estocagem = 0
            SE cagegoria_do_produto = "L"
                custo_de_estocagem = 1
        
    SE categoria_sobre_o_produto == "A" e produto_necessita_de_refrigeracao == "S"
        imposto_do_produto = 2 / 100
    SENAO
        imposto_do_produto = 4 / 100
    
    preco_final_do_produto = preco_do_produto + custo_de_estocagem + imposto_sobre_o_produto
  
  ESCREVA custo_de_estocagem, imposto_do_produto, preco_final_do_produto
  
  SE preco_final_do_produto <= 20
      total_de_produtos_baratos += 1
      classificacao_do_produto = "PRODUTO BARATO"
      
  SE preco_final_do_produto >  20 E preco_final_sobre_produto <=  20
      total_de_produtos_normais += 1
      classificacao_do_produto = "PRODUTO NORMAL"
      
  SE preco_final_do_produto >  100
      total_de_produtos_caros += 1
      classificacao_do_produto = "PRODUTO CARO"
      
  custo_adicional_do_produto = custo_de_estocagem_do_produto + imposto_sobre_o_produto
   
   total_de_custo_adicionais_de_todos_produtos += custo_adicional_do_produto
   total_de_impostos_de_todos_os_produtos += imposto_sobre_o_produto
   
   SE produto == 0
      preco_do_produto_mais_caro = preco_final_do_produto
      preco_do_produto_mais_barato = preco_final_do_produto
   SENAO
      SE preco_do_produto_mais_caro < preco_final_do_produto
          preco_do_produto_mais_caro = preco_final_do_produto
      SE preco_do_produto_mais_barato > preco_final_do_produto
          preco_do_produto_mais_barato = preco_final_do_produto
          
media_dos_valores_adicionais = total_de_custo_adicionaisl_de_todos_produtos / total_de_produtos

ESCREVA media_dos_valores_adicionais
ESCREVA preco_do_produto_mais_caro
ESCREVA preco_do_produto_mais_barato
ESCREVA total_de_produtos_baratos
ESCREVA total_de_produtos_normais
ESCREVA total_de_produtos_caros
   
```
"""

# Digite seu código aqui

"""###23. Faça um programa para calcular a tabuada do 2 até a do 9. USE **DUAS** ESTRUTURAS DE REPETIÇÃO"""

# Digite seu código aqui

"""### 24. Faça um programa que:

* leia um valor N inteiro e positivo
* Calcule e mostre o valor de E, conforme a fórmula:

E = $1 +\frac{1}{1!}+\frac{1}{2!}+\frac{1}{3!}+\frac{1}{4!}+ . . . +\frac{1}{N!}$

USE **DUAS** ESTRUTURAS DE REPETIÇÃO.

NÃO DEVE SER USADA FUNÇÃO PRONTA DA LINGUAGEM PYTHON
"""

# Digite seu código aqui