# -*- coding: utf-8 -*-
"""Ellen Dayane Vivas Rosa Mezaki - 211_Est_DecN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LCzKckvXxc07MabUW_rQpKbP_Vc3chJr

#Lista de exercícios de ESTRUTURA de DECISÃO

### 1.a) Faça um algoritmo que calcule e exiba o salário reajustado de um funcionário de acordo com a seguinte regra: Salário até 500, reajuste de 50%.
"""

salario = float(input('Informe o salário: '))
if salario <= 500:
    salario_reajustado = salario + (salario * 50 / 100)
print('O novo salário é:', salario_reajustado)

"""###1.b) Faça um algoritmo que calcule e exiba o salário reajustado de um funcionário de acordo com a seguinte regra: Salário até 500, reajuste de 50%; Salários maiores que 500, reajuste de 30%."""

salario = float(input('Informe o salário: '))
if salario <= 500:
    salario_reajustado = salario + (salario * 50 / 100)
else:
    salario_reajustado = salario + (salario * 30 / 100)
print('O salário reajustado é:', salario_reajustado)

"""###2. Faça um algoritmo que leia o nome e a idade de uma pessoas, verifique se a idade de uma pessoa é menor ou maior de idade. Considera-se maior de idade uma pessoa com 18 anos ou mais. Como saída o algoritmo deve informar o nome e a idade da pessoa e depois uma mensagem se ela é ou não maior de idade.

"""

nome = str(input('Informe o nome: '))
idade = int(input('Informe a idade: '))
print('O nome é:', nome)
print('A idade é:', idade)
if idade >= 18:
    print('É maior de idade')
else:
    print('É menor de idade')

"""###3. Tendo como dados de entrada a altura e o sexo (M/F) de uma pessoa (M-masculino ou F-feminino), construa um algoritmo que calcule seu peso ideal, utilizando as seguintes fórmulas:
homem: (72.7 * altura) - 58;

mulher: (62.1 * altura) - 44.7


"""

sexo = str(input('Informe o sexo (m ou f): '))
altura = float(input('Informe a altura: '))
if sexo == 'm' or sexo == 'M':
    peso_ideal = (72.7 * altura) - 58
    print('O peso ideal é:', peso_ideal)
if sexo == 'f' or sexo == 'F':
    peso_ideal = (62.1 * altura) - 44.7
    print('O peso ideal é:', peso_ideal)

"""###4. Faça um algoritmo que leia um número inteiro e mostre uma mensagem indicando se este número é par ou ímpar e se é positivo ou negativo.

"""

numero = int(input('Informe um valor:' ))
if numero % 2 == 0:
    print('Este número é par')
else:
    print('Este número é ímpar')
if numero >= 0:
    print('Este número é positivo')
else: 
    print('Este número é negativo')

"""###5. Elabore um algoritmo que informando a idade de um nadador o mesmo terá condições de classificar em uma das seguintes categorias: 
infantil = 5 - 10 anos;
 
juvenil = 11-17 anos; 

adulto = maiores de 18 anos.


"""

idade = int(input('Informe a idade:' ))
if idade >= 5 and idade <= 10:
    print('Pertence a Categoria Infantil')
elif idade >= 11 and idade <= 17:
    print('Pertence a categoria Juvenil')
elif idade >= 18:
    print('Pertence a categoria Adulto')
elif idade < 5:
    print('Não pertence a nenhuma categoria')

"""###6. Um banco concederá um crédito especial aos seus clientes, variável com o saldo médio no último ano. Faça um algoritmo que leia o saldo médio de um cliente e calcule o valor do crédito de acordo com a tabela a seguir. Mostre uma mensagem informando o saldo médio e o valor do crédito.
        Saldo médio
        * de 0 a 200 nenhum crédito
        * de 201 a  400 20% do valor do saldo médio
        * de 401 a  600 30% do valor do saldo médio
        * acima de 601 40% do valor do saldo médio

"""

saldo_medio = float(input('Informe o valor do Saldo Médio:' ))
if saldo_medio >= 0 and saldo_medio <= 200:
    credito = 0
    print('nenhum crédito')
elif saldo_medio >= 201 and saldo_medio <= 400:
    credito = saldo_medio * 20 / 100
elif saldo_medio >= 401 and saldo_medio <= 600:
    credito = saldo_medio * 30 / 100
elif saldo_medio > 601:
    credito = saldo_medio * 40 / 100
print('O valor do Saldo Médio é:',saldo_medio)
print('O valor do Crédito é:', credito)

"""###7. A Organização Mundial de Saúde usa a seguinte tabela para determinar a condição de um adulto, para isso desenvolva um algoritmo para calcular o Índice de Massa Corporal (IMC) e apresenta-lo, dado pela fórmula: 
    IMC = peso / (altura)2   (o número 2 significa, elevado ao quadrado)

CONDIÇÃO |  IMC em adultos |
 ---|---
Abaixo do peso  |	Abaixo de 18.5  |
No peso normal	|	Entre 18.5 e 25|
Acima do peso	|	Entre 25.1 e 30|
Obeso		    |	Acima de 30|
"""

peso = float(input('Informe o peso:' ))
altura = float(input('Informe a altura:' ))
imc = peso / altura**2
if imc < 18.5:
    print('Abaixo do peso')
elif imc >= 18.5 and imc <= 25:
    print('Peso normal')
elif imc >= 25.1 and imc <= 30:
    print('Acima do peso')
else:
    print('Obeso')

"""### 8. A nota final de um estudante é calculada a partir de três notas atribuídas, respectivamente, a um trabalho de laboratório, a uma avaliação semestral e a um exame final. A média das três notas mencionadas obedece aos pesos a seguir:

 NOTA |  PESO |
 ---|---
Trabalho de laboratório  |   2   |
Avaliação semestral      |   3   |
Exame final              |   5   |

### Faça um programa que receba as três notas, calcule e mostre a média ponderada e o conceito que segue a tabela

MÉDIA PONDERADA    | CONCEITO|
---|---
8,0 <= média <= 10  |    A 
7,0 <= média < 8,0  |    B 
6,0 <= média < 7,0  |    C 
5,0 <= média < 6,0  |    D 
 0,0 <= média < 5,0  |    E
       
media_ponderada = (nota_traballho * 2 + avaliacao_semestral * 3 + exame_final * 5) / 10


"""

trabalho_laboratorio = float(input('Informe a nota do Trabalho de laboratório:' ))
avaliacao_semestral = float(input('Informe a nota da Avaliação semestral:' ))
exame_final = float(input('Informe a nota do Exame Final:' ))
media_ponderada = (trabalho_laboratorio * 2 + avaliacao_semestral * 3 + exame_final * 5) / 10
print(f'A média ponderada é: {media_ponderada:.2f}')
if media_ponderada >= 8.0 and media_ponderada <= 10.0:
    print('Conceito A')
elif media_ponderada >= 7.0 and media_ponderada < 8.0:
    print('Conceito B')
elif media_ponderada >= 6.0 and media_ponderada < 7.0:
    print('Conceito C')
elif media_ponderada >= 5.0 and media_ponderada < 6.0:
    print('Conceito D')
elif media_ponderada >= 0.0 and media_ponderada < 5.0:
    print('Conceito E')

"""### 9. Faça um programa que receba três notas de um aluno, calcule e mostre a média aritmética e a mensagem constante na tabela a seguir. Aos alunos que ficaram para exame, calcule e mostre a nota que deverão tirar para serem aprovados, considerando que a média exigida é 6,0.

MÉDIA ARITMÉTICA | MENSAGEM
    ---|---
    0 <= média < 3 |Reprovado
    3 <= média < 6|Exame
    6 <= média <= 10|Aprovado

```
SE media >= 3 E media < 6
    ESCREVA “Exame”
    nota_exame = 12 - media
    ESCREVA “Você deve tirar a nota”, nota_exame, “para ser aprovado.”

"""

trabalho = float(input('Informe a nota do trabalho:' ))
atividade_avaliativa = float(input('Informe a nota da atividade avaliativa:' ))
prova = float(input('Informe a nota da prova:' ))
media_aritmetica = (trabalho + atividade_avaliativa + prova) / 3
if media_aritmetica >= 0 and media_aritmetica < 3:
    print('Reprovado')
if media_aritmetica >= 3 and media_aritmetica < 6:
    print('Exame')
    nota_exame = 12 - media_aritmetica
    print(f'Você deve tirar a nota {nota_exame:.2f}', 'para ser aprovado.')
if media_aritmetica >= 6 and media_aritmetica <= 10:
    print('Aprovado')

"""### 10. Faça um programa que receba dois números e mostre o maior.

"""

numero1 = float(input('Digite um número:' ))
numero2 = float(input('Digite outro número:' ))
if numero1 > numero2:
    print('Primeiro número maior')
elif numero1 < numero2:
    print('Segundo número maior')
else:
    print('Os números tem o mesmo valor')

"""### 11. Faça um programa que receba três números e mostre-os em ordem crescente. Suponha que o usuário digitará três números diferentes.

```
SE numero1 < numero2 E numero1 < numero3
    SE numero2 < numero3
        ESCREVA “A ordem crescente é: “,numero1,“-”,numero2,“-”,numero3
    SENÃO
        ESCREVA “A ordem crescente é: “,numero1,“-”,numero3,“-”,numero2
SE numero2 < numero1 E numero2 < numero3
    SE numero1 < numero3
        ESCREVA “A ordem crescente é: “,numero2,“-”,numero1,“-”,numero3
    SENÃO
        ESCREVA “A ordem crescente é: “,numero2,“-”,numero3,“-”,numero1
SE numero3 < numero1 E numero3 < num2
    SE numero1 < numero2
        ESCREVA “A ordem crescente é: “,numero3,“-”,numero1,“-”,numero2
    SENÃO 
        ESCREVA “A ordem crescente é: “,numero3,“-”,numero2,“-”,numero1
  ```
"""

numero1 = float(input('Digite um número:' ))
numero2 = float(input('Digite outro número:' ))
numero3 = float(input('Digite o terceiro número:' ))
if numero1 < numero2 and numero1 < numero3:
    if numero2 < numero3:
        print('A ordem crescente é: ',numero1,"-",numero2,"-",numero3)
    else:
        print('A ordem crescente é: ',numero1,"-",numero3,"-",numero2)
if numero2 < numero1 and numero2 < numero3:
    if numero1 < numero3:
        print('A ordem crescente é: ',numero2,"-",numero1,"-",numero3)
    else:
        print('A ordem crescente é: ',numero2,"-",numero3,"-",numero1)
if numero3 < numero1 and numero3 < numero2:
    if numero1 < numero2:
        print('A ordem crescente é: ',numero3,"-",numero1,"-",numero2)
    else:
        print('A ordem crescente é: ',numero3,"-",numero2,"-",numero1)

"""### 12. Faça um programa que receba três números obrigatoriamente em ordem crescente e um quarto número que não siga essa regra. Mostre, em seguida, os quatro números em ordem decrescente. Suponha que o usuário digitará quatro números diferentes.

```code
SE numero4 > numero3
    ESCREVA “A ordem decrescente é: “,numero4,“-”,numero3,“-”,numero2,“-”,numero1
SENÃO SE numero4 > numero2 E numero4 < numero3
    ESCREVA “A ordem decrescente é: “,numero3,“-”,numero4,“-”,numero2,“-”,numero1
SENÃO SE numero4 > numero1 E numero4 < numero2
    ESCREVA “A ordem decrescente é: “,numero3,“-”,numero2,“-”,numero4, “-”,numero1
SENÃO SE numero4 < numero1
    ESCREVA “A ordem decrescente é: “,numero3,“-”,numero2,“-”,numero1,“-”,numero4
```
"""

numero1 = float(input("Digite um número: "))
numero2 = float(input("Digite um número maior que o primeiro número: "))
numero3 = float(input("Digite um número maior que o segundo número: "))
numero4 = float(input("Digite um número aleatório: "))
if numero4 > numero3:
    print("A ordem decrescente é: ",numero4,"-",numero3,"-",numero2,"-",numero1)
elif numero4 > numero2 and numero4 < numero3:
    print("A ordem decrescente é: ",numero3,"-",numero4,"-",numero2,"-",numero1)
elif numero4 > numero1 and numero4 < numero2:
    print("A ordem decrescente é: ",numero3,"-",numero2,"-",numero4, "-",numero1)
elif numero4 < numero1:
    print("A ordem decrescente é: ",numero3,"-",numero2,"-",numero1,"-",numero4)

"""### 13. Faça um programa que receba quatro valores: I, A, B e C. Desses valores, I é inteiro e positivo, A, B e C são reais. Escreva os números A, B e C obedecendo à tabela a seguir.

*Suponha que o valor digitado para I seja sempre um valor válido, ou seja, 1, 2 ou 3, e que os números digitados sejam diferentes um do outro.*

  |VALOR DE I | FORMA A ESCREVER|
  |---|---|
  |1                  |A, B e C em ordem crescente.|
  |2                  |A, B e C em ordem decrescente|
  |3                  |O maior fica entre os outros dois números.|

  ```code
SE I == 1
    SE A<B E A<C
        SE B<C
            ESCREVA “A ordem crescente dos números é:”,A,” -”,B,”-”,C
        SENÃO
            ESCREVA “A ordem crescente dos números é:”,A,” -”,C,”-”,B
    SE B<A E B<C
        SE A<C
            ESCREVA “A ordem crescente dos números é:”,B,”-”,A,”-”,C
        SENÃO
            ESCREVA “A ordem crescente dos números é: “,B,”-”,C,”-”,A
    SE C<A E C<B
        SE A<B
            ESCREVA “A ordem crescente dos números é: “,C,”-”,A,”-”,B
        SENÃO
            ESCREVA “A ordem crescente dos números é: “,C,”-”,B,”-”,A
SE I == 2
    SE A>B E A>C
        SE B>C
            ESCREVA “A ordem decrescente dos números é: “,A,” -”,B,”-”,C
        SENÃO
            ESCREVA “A ordem decrescente dos números é: “,A,” -”,C,”-”,B
    SE B>A E B>C
        SE A>C
            ESCREVA “A ordem decrescente dos números é: “,B,” -”,A,”-”,C
        SENÃO
            ESCREVA “A ordem decrescente dos números é: “,B,” -”,C,”-”,A
    SE C>A E C>B
        SE A>B
            ESCREVA “A ordem decrescente dos números é: “,C,” -”,A,”-”,B
        SENÃO
            ESCREVA “A ordem decrescente dos números é: “,C,” -”,B,”-”,A
SE I == 3
    SE A>B E A>C
        ESCREVA “A ordem desejada é: “,B,”-”,A,”-”,C
    SE B>A E B>C
        ESCREVA “A ordem desejada é: “,A,”-”,B,”-”,C
    SE C>A E C>B
        ESCREVA “A ordem desejada é: “,A,”-”,C,”-”,B
```
"""

I = int(input('Escolha um dos seguintes números 1,2 ou 3: '))
A = float(input("Digite um número: "))
B = float(input("Digite um número: "))
C = float(input("Digite um número: "))
if I == 1:
    if A<B and A<C:
        if B<C:
            Print("A ordem crescente dos números é: ",A,"-",B,"-",C)
        else:
            print("A ordem crescente dos números é: ",A,"-",C,"-",B)
    if B<A and B<C:
        if A<C:
            print("A ordem crescente dos números é: ",B,"-",A,"-",C)
        else:
            print("A ordem crescente dos números é: ",B,"-",C,"-",A)
    if C<A and C<B:
        if A<B:
            print("A ordem crescente dos números é: ",C,"-",A,"-",B)
        else:
            print("A ordem crescente dos números é: ",C,"-",B,"-",A)
if I == 2:
    if A>B and A>C:
        if B>C:
            print("A ordem decrescente dos números é: ",A,"-",B,"-",C)
        else:
            print("A ordem decrescente dos números é: ",A,"-",C,"-",B)
    if B>A and B>C:
        if A>C:
            print("A ordem decrescente dos números é: ",B,"-",A,"-",C)
        else:
            print("A ordem decrescente dos números é: ",B,"-",C,"-",A)
    if C>A and C>B:
        if A>B:
            print("A ordem decrescente dos números é: ",C,"-",A,"-",B)
        else:
            print("A ordem decrescente dos números é: ",C,"-",B,"-",A)
if I == 3:
    if A>B and A>C:
        print("A ordem desejada é: ",B,"-",A,"-",C)
    if B>A and B>C:
        print("A ordem desejada é: ",A,"-",B,"-",C)
    if C>A and C>B:
        print("A ordem desejada é: ",A,"-",C,"-",B)

"""### 14. Faça um programa que mostre o menu de opções a seguir, receba a opção do usuário e os dados necessários para executar cada operação.

    Menu de opções:
    1. Somar dois números.
    2. Raiz quadrada de um número.

Observação: raiz = numero ** (1/2), ou 
import math
raiz = math.sqrt(numero)
      
"""

numero1 = float(input('Informe um número: '))
numero2 = float(input('Informe outro número: '))
escolha = int(input('Escolha uma opção entre 1 ou 2: '))
if escolha == 1:
    somar = numero1 + numero2
    print('O resultado é: ', somar)
elif escolha == 2:
    raiz = numero1 ** (1/2)
    print('O resultado é: ', raiz)

"""### 15. Faça um programa que mostre a data e a hora do sistema nos seguintes formatos: **dia/mês/ano – mês por extenso e hora:minuto**.

Observação: ***from*** carrega um módulo/biblioteca da linguagem Python e o ***import*** é usado para informar qual objeto desta biblioteca queremos importar/carregar no nosso programa

    from datetime import datetime
    #captura a data e hora de hoje de algum país onde esta o servidor que executa nosso programa em Python
    #quando eu testei, o servidor era de Dacar-Senegal
    hoje = datetime.now()
    print ('Ano atual.:',hoje.year)
    print ('Mês.......:',hoje.month)
    print ('Dia.......:',hoje.day)
    print ('Hora......:',hoje.hour)
    print ('Minuto....:',hoje.minute)
    print ('Segundos..:',hoje.second)
"""

from datetime import datetime
hoje = datetime.now()
print ('Ano atual.:',hoje.year)
print ('Mês.......:',hoje.month)
print ('Dia.......:',hoje.day)
print ('Hora......:',hoje.hour)
print ('Minuto....:',hoje.minute)
print ('Segundos..:',hoje.second)
if hoje.month == 1:
    mes = 'janeiro'
    print(hoje.day,'/janeiro/',hoje.year,'  ',hoje.hour,':',hoje.minute)
if hoje.month == 2:
    mes = 'fevereiro'
    print(hoje.day,'/fevereiro/',hoje.year,'  ',hoje.hour,':',hoje.minute)
if hoje.month == 3:
    mes = 'março'
    print(hoje.day,'/março/',hoje.year,'  ',hoje.hour,':',hoje.minute)
if hoje.month == 4:
    mes = 'abril'
    print(hoje.day,'/abril/',hoje.year,'  ',hoje.hour,':',hoje.minute)
if hoje.month == 5:
    mes = 'maio'
    print(hoje.day, ' /maio/',hoje.year,'  ',hoje.hour,':',hoje.minute)
if hoje.month == 6:
    mes = 'junho'
    print(hoje.day,'/junho/',hoje.year,'  ',hoje.hour,':',hoje.minute)
if hoje.month == 7:
    mes = 'julho'
    print(hoje.day,'/julho/',hoje.year,'  ',hoje.hour,':',hoje.minute)
if hoje.month == 8:
    mes = 'agosto'
    print(hoje.day,'/agosto/',hoje.year,'  ',hoje.hour,':',hoje.minute)
if hoje.month == 9:
    mes = 'setembro'
    print(hoje.day,'/setembro/',hoje.year,'  ',hoje.hour,':',hoje.minute)
if hoje.month == 10:
    mes = 'outubro'
    print(hoje.day,'/outubro/',hoje.year,'  ',hoje.hour,':',hoje.minute)
if hoje.month == 11:
    mes = 'novembro'
    print(hoje.day, ' /novembro/',hoje.year,'  ',hoje.hour,':',hoje.minute)
if hoje.month == 12:
    mes = 'dezembro'
    print(hoje.day,'/dezembro/',hoje.year,'  ',hoje.hour,':',hoje.minute)

"""### 16. Faça um programa que determine a data cronologicamente maior entre duas datas fornecidas pelo usuário. Cada data deve ser composta por três valores inteiros, em que o primeiro representa o dia, o segundo, o mês e o terceiro, o ano.

  ```code
  SE ano1 > ano2
      ESCREVA “A maior data é: “,dia1,”-”,mes1,”-”,ano1
  SENÃO SE ano2>ano1
      ESCREVA “A maior data é: “,dia2,”-”,mes2,”-”,ano2
  SENÃO SE mes1>mes2
      ESCREVA “A maior data é: “,dia1,”-”,mes1,”-”,ano1
  SENÃO SE mes2>mes1
      ESCREVA “A maior data é: “,dia2, “-”,mes2,”-”,ano2
  SENÃO SE dia1>dia2
      ESCREVA “A maior data é: “-”,dia1,”-”,mia1,” -”,ano1
  SENÃO SE dia2>dia1
      ESCREVA “A maior data é: “,dia2,” -”,mes2,”-”,ano2
  SENÃO
      ESCREVA “As datas são iguais!”
  ```
"""

dia1 = int(input('Informe um dia: '))
mes1 = int(input('Informe um mês: '))
ano1 = int(input('Informe um ano: '))
dia2 = int(input('Informe outro dia: '))
mes2 = int(input('Informe outro mês: '))
ano2 = int(input('Informe outro ano: '))
if ano1 > ano2:
    print('A maior data é: ',dia1,'-',mes1,'-',ano1)
elif ano2 > ano1:
    print('A maior data é: ',dia2,'-',mes2,'-',ano2)
elif mes1 > mes2:
    print('A maior data é: ',dia1,'-',mes1,'-',ano1)
elif mes2 > mes1:
    print('A maior data é: ',dia2, '-',mes2,'-',ano2)
elif dia1 > dia2:
    print('A maior data é: ',dia1,'-',mes1,'-',ano1)
elif dia2 > dia1:
    print('A maior data é: ',dia2,'-',mes2,'-',ano2)
else:
    print('As datas são iguais!')

"""### 17. Faça um programa que receba a hora do início de um jogo e a hora do término (cada hora é composta por duas variáveis inteiras: hora e minuto). Calcule e mostre a duração do jogo (horas e minutos), sabendo que o tempo máximo de duração do jogo é de 24 horas e que ele pode começar em um dia e terminar no dia seguinte.
    SE min_inicial > min_f
        minuto_final = minuto_final + 60
        hora_final = hora_final – 1
    SE hora_inicial > hora_final
        hora_final = hora_final + 24
    minuto_duracao = minuto_final - minuto_inicial
    hora_duracao = hora_final - hora_inicial
"""

hora_inicial = int(input('Digite a hora de início do jogo: '))
minutos_inicial = int(input('Digite os minutos do início do jogo: '))
hora_final = int(input('Digite a hora final do jogo: '))
minutos_final = int(input('Digite os minutos do final do jogo: '))
if minutos_inicial > minutos_final:
    minutos_final = minutos_final + 60
    hora_final = hora_final - 1
if hora_inicial > hora_final:
    hora_final = hora_final + 24
minuto_duracao = minutos_final - minutos_inicial
hora_duracao = hora_final - hora_inicial
print('O tempo de duração do jogo é: ', hora_duracao ,'horas e' ,minuto_duracao,'minutos.')

"""### 18. Faça um programa que receba o código correspondente ao cargo de um funcionário e seu salário atual e mostre o cargo, o valor do aumento e seu novo salário. Os cargos estão na tabela a seguir.

  |CÓDIGO|CARGO|PERCENTUAL|
  |---|---|---|
  |1|Escriturário|50%|
  |2|Secretário|35%|
  |3|Caixa|20%|
  |4|Gerente|10%|
  |5|Diretor|Não tem aumento|

```code
SE cargo == 1
    ESCREVA “O cargo é Escriturário”
    aumento = salario * 50 / 100
    ESCREVA “O valor do aumento é: “, aumento
    novo_sal = salario + aumento
    ESCREVA “O novo salário é: “, novo_sal
SENÃO SE cargo == 2
    ESCREVA “O cargo é Secretário”
    aumento = salario * 35 / 100
    ESCREVA “O valor do aumento é: “, aumento
    novo_sal = salario + aumento
    ESCREVA “O novo salário é: “, novo_sal]
SENÃO SE cargo == 3
    ESCREVA “O cargo é Caixa”
    aumento = salario * 20 / 100
    ESCREVA “O valor do aumento é: “, aumento
    novo_sal = salario + aumento
    ESCREVA “O novo salário é: “,novo_sal
SENÃO SE cargo == 4
    ESCREVA “O cargo é Gerente”
    aumento = salario * 10 / 100
    ESCREVA “O valor do aumento é: “, aumento
    novo_sal = salario + aumento
    ESCREVA “O novo salário é: “, novo_sal
SENÃO SE cargo == 5
    ESCREVA “O cargo é Diretor”
    aumento = salario * 0 / 100
    ESCREVA “O valor do aumento é: “, aumento
    novo_sal = salario + aumento
    ESCREVA “O novo salário é: “, novo_sal
```
"""

cargo = int(input('Informe o código do cargo (1,2,3,4 ou 5): '))
salario = float(input('Informe o salário do cargo do código informado: '))
if cargo == 1:
    print('O cargo é Escriturário')
    aumento = salario * 50 / 100
    print('O valor do aumento é: ', aumento)
    novo_salario = salario + aumento
    print('O novo salário é: ', novo_salario)
elif cargo == 2:
    print('O cargo é Secretário')
    aumento = salario * 35 / 100
    print('O valor do aumento é: ', aumento)
    novo_salario = salario + aumento
    print('O novo salário é: ', novo_salario)
elif cargo == 3:
    print('O cargo é Caixa')
    aumento = salario * 20 / 100
    print('O valor do aumento é: ', aumento)
    novo_salario = salario + aumento
    print('O novo salário é: ', novo_salario)
elif cargo == 4:
    print('O cargo é Gerente')
    aumento = salario * 10 / 100
    print('O valor do aumento é: ', aumento)
    novo_salario = salario + aumento
    print('O novo salário é: ', novo_salario)
elif cargo == 5:
    print('O cargo é Diretor')
    aumento = salario * 0 / 100
    print('O valor do aumento é: ', aumento)
    novo_salario = salario + aumento
    print('O novo salário é: ', novo_salario)

"""### 19. Faça um programa que apresente o menu a seguir, permita ao usuário escolher a opção desejada, receba os dados necessários para executar a operação e mostre o resultado. Verifique a possibilidade de opção inválida e não se preocupe com restrições, como salário negativo.

    Menu de opções
    1. Imposto
    2. Novo salário
    3. Classificação
    Digite a opção desejada:

*Na opção 1: receber o salário de um funcionário, calcular e mostrar o valor do imposto usando as regras a seguir.*

  |SALÁRIO|PERCENTUAL DO IMPOSTO|
  |---|---|
  |Menor que  500,00|5%|
  |De  500,00 (inclusive) a  850,00 (inclusive)|10%|
  |Acima de  850,00|15%|

*Na opção 2: receber o salário de um funcionário, calcular e mostrar o valor do novo salário, usando as regras a seguir.*

  |SALÁRIO|AUMENTO|
  |---|---|
  |Maior que  1.500,00| 25,00|
  |De  750,00 (inclusive) a  1.500,00 (inclusive)| 50,00|
  |De  450,00 (inclusive) a  750,00| 75,00|
  |Menor que  450,00| 100,00|

*Na opção 3: receber o salário de um funcionário e mostrar sua classificação usando a tabela a seguir.*

|SALÁRIO|CLASSIFICAÇÃO|
|---|---|
|Até  700,00 (inclusive)|Mal remunerado|
|Maiores que  700,00|Bem remunerado|

"""

menu = int(input('Escolha a opção desejada entre 1, 2 ou 3: '))
salario = float(input('Informe o salário: '))
if menu == 1:
    if salario < 500:
        imposto = salario * 5 / 100
        print('O valor do imposto é: ', imposto)
    if salario >= 500 and salario <= 850:
        imposto = salario * 10 / 100
        print('O valor do imposto é: ', imposto)
    if salario > 850:
        imposto = salario * 15 / 100
        print('O valor do imposto é: ', imposto)
if menu == 2:
    if salario < 450:
        aumento_salario = salario + 100
        print('O valor do novo salário é: ', aumento_salario)
    if salario >= 450 and salario < 750:
        aumento_salario = salario + 75
        print('O valor do novo salário é: ', aumento_salario)
    if salario >= 750 and salario <= 1500:
        aumento_salario = salario + 50
        print('O valor do novo salário é: ', aumento_salario)
    if salario > 1500:
        aumento_salario = salario + 25
        print('O valor do novo salário é: ', aumento_salario)
if menu == 3:
    if salario <= 700:
        print('Mal remunerado')
    if salario > 700:
        print('Bem remunerado')

"""###20. Faça um programa que receba o salário inicial de um funcionário, calcule e mostre o novo salário, acrescido de bonificação e de auxílio escola.

|SALÁRIO|BONIFICAÇÃO|
|---|---|
|Até  500,00|5% do salário|
|Entre  500,00 e 1.200,00|12% do salário|
|Acima de  1.200,00|Sem bonificação|
>
|SALÁRIO|AUXÍLIO ESCOLA|
|---|---|
|Até  600,00| 150,00|
|Acima de  600,00| 100,00|

novo_salario = salario + bonificacao + auxílio escola
"""

salario_inicial = float(input('Informe o salário inicial: '))
if salario_inicial <= 500:
    bonificacao = salario_inicial * 5 / 100
    auxilio_escola = 150
    novo_salario = salario_inicial + bonificacao + auxilio_escola
    print('O novo salário é: ', novo_salario)
if salario_inicial > 500 and salario_inicial <= 1200:
    bonificacao = salario_inicial * 12 / 100
    if auxilio_escola > 500 and auxilio_escola <= 600:
        auxilio_escola = 150
        novo_salario = salario_inicial + bonificacao + auxilio_escola
        print('O novo salário é: ', novo_salario)
    if auxilio_escola < 600:
        auxilio_escola = 100
        novo_salario = salario_inicial + bonificacao + auxilio_escola
        print('O novo salário é: ', novo_salario)
if salario_inicial > 1200:
    bonificacao = 0
    auxilio_escola = 100
    novo_salario = salario_inicial + bonificacao + auxilio_escola
    print('O novo salário é: ', novo_salario)

"""### 21. Faça um programa que receba o valor do salário mínimo, o número de horas trabalhadas, o número de dependentes do funcionário e a quantidade de horas extras trabalhadas. Calcule e mostre o salário a receber do funcionário de acordo com as regras a seguir:

  * O valor da hora trabalhada é igual a 1/5 do salário mínimo.
  * O salário do mês é igual ao número de horas trabalhadas multiplicado pelo valor da hora trabalhada.
  * Para cada dependente, acrescentar  32,00.
  * Para cada hora extra trabalhada, calcular o valor da hora * trabalhada acrescida de 50%.
  * O salário bruto é igual ao salário do mês mais o valor dos dependentes mais o valor das horas extras.
  * Calcular o valor do impostoosto de renda retido na fonte de acordo com a tabela a seguir:

|IRFF|SALÁRIO BRUTO|
|---|---|
|Isento|Inferior a  200,00|
|10%|De  200,00 até 500,00|
|20%|Superior a  500,00|

  * O salário líquido é igual ao salário bruto menos IRRF.
  * A gratificação é de acordo com a tabela a seguir:

|SALÁRIO LÍQUIDO|GRATIFICAÇÃO|
|---|---|
|Até 350,00| 100,00|
|Superior a  350| 50,00|

  * O salário a receber do funcionário é igual ao salário líquido mais a gratificação.

  ```code
  LEIA salario_minimo, numero_horas_trabalhadas, numero_dependentes, numero_horas_extras
  
  valor_hora = 1/5 * salario_minimo
  salario_mes = numero_horas_trabalhadas * valor_hora
  valor_dependentes = 32 * numero_dependentes
  valor_hora_extra = numero_horas_extras * (valor_hora + (valor_hora * 50/100))
  salario_bruto =salario_mes + valor_dependentes + valor_hora_extra
  
  SE salario_bruto < 200
        imposto = 0
  SENÃO SE salario_bruto >= 200 E salario_bruto <= 500
        imposto = salario_bruto * 10/100
  SENÃO SE salario_bruto > 500
        imposto = salario_bruto * 20/100
  salario_liquido = salario_bruto – imposto
  SE salario_liquido <= 350
        gratificacao = 100
  SENÃO
        gratificacao = 50
  salario_a_receber = salario_liquido + gratificacao
  
  ESCREVA salario_a_receber
  ```
"""

salario_minimo = float(input('Informe o salário mínimo: '))
numero_horas_trabalhadas = float(input('Informe a quantidade de horas trabalhadas: '))
numero_dependentes = int(input('Informe o número de dependentes: '))
numero_horas_extras = float(input('Informe o número de horas extras: ')) 
valor_hora = 1/5 * salario_minimo
salario_mes = numero_horas_trabalhadas * valor_hora
valor_dependentes = 32 * numero_dependentes
valor_hora_extra = numero_horas_extras * (valor_hora + (valor_hora * 50/100))
salario_bruto =salario_mes + valor_dependentes + valor_hora_extra
if salario_bruto < 200:
    imposto = 0
elif salario_bruto >= 200 and salario_bruto <= 500:
    imposto = salario_bruto * 10/100
elif salario_bruto > 500:
    imposto = salario_bruto * 20/100
salario_liquido = salario_bruto - imposto
if salario_liquido <= 350:
    gratificacao = 100
else:
    gratificacao = 50
salario_a_receber = salario_liquido + gratificacao
print(' O salário a receber é: ', salario_a_receber)

"""### 22 Um supermercado deseja reajustar os preços de seus produtos usando o seguinte critério: o produto poderá ter seu preço aumentado ou diminuído. Para o preço ser alterado, o produto deve preencher pelo menos um dos requisitos a seguir:

|VENDA MÉDIA MENSAL|PREÇO ATUAL|% DE AUMENTO|% DE DIMINUIÇÃO|
|---|--|---|---|
|< 500|<  30000|10|-|
|\>= 500 e <1200|\>=  30.00 e <  80.00|15|-|
|\>= 1200|\>=  80.00|-|20|

* Faça um programa que receba o preço atual e a venda média mensal do produto, calcule e mostre o novo preço.

```code
LEIA preco_atual, media_mensal_vendas

SE media_mensal_vendas < 500 OU preco_atual < 30
    novo_preco = preco_atual + 10/100 * preco_atual
SENÃO SE media_mensal_vendas >= 500 E media_mensal_vendas < 1200 OU preco_atual >= 30 E preco_atual<80
    novo_preco = preco_atual + 15 / 100 * preco_atual
SENÃO SE venda >= 1200 OU preco_atual >= 80
    novo_preco = preco_atual – 20 / 100 * preco_atual
      
ESCREVA novo_preco
```
"""

preco_atual = float(input('Informe o preço atual do produto: '))
media_mensal_vendas = int(input('Informe a média mensal de vendas: '))
if media_mensal_vendas < 500 or preco_atual < 30:
    novo_preco = preco_atual + 10 / 100 * preco_atual
elif media_mensal_vendas >= 500 and media_mensal_vendas < 1200 or preco_atual >= 30 and preco_atual < 80:
    novo_preco = preco_atual + 15 / 100 * preco_atual
elif media_mensal_vendas >= 1200 or preco_atual >= 80:
    novo_preco = preco_atual - 20 / 100 * preco_atual
print('O novo preço é: ', novo_preco)

"""### 23. Faça um programa para resolver equações do 2 o grau.

**ax² + bx + c = 0**

A variável *a* deve ser diferente de zero*

  * delta = b ** 2 - 4 * a * c
  * delta < 0.  **Não existe raiz real**
  * delta = 0. **Existe uma raiz real**
    * x = (-b) / (2 * a)
  * delta > 0. **Existem duas raízes reais**
    * x1 = (-b + delta )/ (2 * a)
    * x2 = (-b - delta )/ (2 * a)

```code
LEIA a, b, c
SE a = 0
    ESCREVA “Estes valores não formam uma equação de segundo grau” 
SENÃO
    delta = (b * b) – ( 4 * a * c)
    SE delta < 0
        ESCREVA “Não existe raiz real”
    SE delta = 0
        ESCREVA “Existe uma raiz real”
        x1 = (– b) / (2 * a)
        ESCREVA x1
    SE delta > 0
        ESCREVA “Existem duas raízes reais”
        x1 = (– b) + raiz(delta) / (2 * a)
        x2 = (– b) - raiz(delta) / (2 * a)
        ESCREVA(x1, x2)
```
"""

a = float(input('Digite um número: '))
b = float(input('Digite outro número: '))
c = float(input('Digite mais um número: '))
if a == 0:
    print('Estes valores não formam uma equação de segundo grau') 
else:
    delta = (b * b) - (4 * a * c)
    if delta < 0:
        print('Não existe raiz real')
    if delta == 0:
        print('Existe uma raiz real')
        x1 = (- b) / (2 * a)
        print('A raiz real é: ', x1)
    if delta > 0:
        print('Existem duas raízes reais')
        x1 = (- b) + (delta) / (2 * a)
        x2 = (- b) - (delta) / (2 * a)
        print('As raizes reais são: ', x1, x2)

"""### 24. Dados três valores X, Y e Z, verifique se eles podem ser os comprimentos dos lados de um triângulo e, se forem, verifique se é um triângulo equilátero, isósceles ou escaleno. Se eles não formarem um triângulo, escreva uma mensagem.
Considere que:
* o comprimento de cada lado de um triângulo é menor que a soma dos outros dois lados;
* chama-se equilátero o triângulo que tem três lados iguais;
* denomina-se isósceles o triângulo que tem o comprimento de dois lados iguais;
* recebe o nome de escaleno o triângulo que tem os três lados diferentes.

```code
LEIA x, y, z
SE x < y + z E y < x + z E z < x + y
    SE x = y E y = z
        ESCREVA “Triângulo Equilátero”
    SENÃO SE x = y OU x = z OU y = z
        ESCREVA “Triângulo Isósceles”
    SENÃO SE x ≠ y E x ≠ z E y ≠ z
        ESCREVA “Triângulo Escaleno”
SENÃO
    ESCREVA “Essas medidas não formam um triângulo”
```
"""

x = float(input('Digite o comprimento: '))
y = float(input('Digite o comprimento: '))
z = float(input('Digite o comprimento: '))
if x < y + z and y < x + z and z < x + y:
    if x == y and y == z:
        print('Triângulo Equilátero')
    elif x == y or x == z or y == z:
        print('Triângulo Isósceles')
    elif x != y and x != z and y != z:
        print('Triângulo Escaleno')
else:
    print('Essas medidas não formam um triângulo')

"""### 25. Faça um programa que receba a altura e peso de uma pessoa. De acordo com a tabela a seguir, verifique e mostre a classificação dessa pessoa.

|ALTURA|ATÉ 60|ENTRE 60 E 90 (INCLUSIVE)|ACIMA DE 90|
|---|---|---|---|
|Menores que 1,20|A|D|G|
|De 1,20 a 1,70|B|E|H|
|Maiores que 1,70|C|F|I|

```code
LEIA altura, peso
SE altura < 1.20
    SE peso <= 60
        ESCREVA “A”
    SENÃO SE peso > 60 E peso <= 90
        ESCREVA “D”
    SENÃO SE peso > 90
        ESCREVA “G”
SENÃO SE altura >= 1.20 E altura <= 1.70
    SE peso <= 60
        ESCREVA “B”
    SENÃO SE peso > 60 E peso <= 90
        ESCREVA “E”
    SENÃO SE peso > 90
        ESCREVA “H”
SENÃO SE altura > 1.70
    SE peso <= 60
        ESCREVA “C”
    SENÃO SE peso > 60 E peso <= 90
        EESCREVA “F”
    SENÃO SE peso > 90
        ESCREVA “I”
```
"""

altura = float(input('Informe a altura: '))
peso = float(input('Informe o peso: '))
if altura < 1.20:
    if peso <= 60:
        print('A classificação é: A')
    elif peso > 60 and peso <= 90:
        print('A classificação é: D')
    elif peso > 90:
        print('A classificação é: G')
elif altura >= 1.20 and altura <= 1.70:
    if peso <= 60:
        print('A classificação é: B')
    elif peso > 60 and peso <= 90:
        print('A classificação é: E')
    elif peso > 90:
        print('A classificação é: H')
elif altura > 1.70:
    if peso <= 60:
        print('A classificação é: C')
    elif peso > 60 and peso <= 90:
        print('A classificação é: F')
    elif peso > 90:
        print('A classificação é: I')

"""### 26. Faça um programa que receba:

* O código de um produto comprado, supondo que a digitação do código do produto seja sempre válida, isto é, um número * inteiro entre 1 e 10.
* O peso do produto em quilos.
* O código do país de origem, supondo que a digitação do  código seja sempre válida, isto é, um número inteiro entre 1 e 3.

|CÓDIGO DO PAÍS DE ORIGEM|IMPOSTO|
|---|---|
|1|0%|
|2|15%|
|3|25%|

|CÓDIGO DO PAÍS DO PRODUTO|Preço por grama|
|---|---|
|1 a 4|10|
|5 a 7|25|
|8 a 10|35|

Calcule e mostre:
* o peso do produto convertido em gramas;
* o preço total do produto comprado;
* valor do imposto, sabendo que ele é cobrado sobre o * preço total do produto comprado e dependendo país de origem;
* o valor total, preço total do produto mais imposto.

```code
LEIA codigo_produto, peso_quilos, codigo_pais
peso_em_gramas = peso_quilos * 1000
ESCREVA peso_em_gramas
SE codigo_produto >= 1 E codigo_produto <= 4
   preco_por_grama = 10
SENÃO SE codigo_produto >= 5 E codigo_produto <= 7
   preco_por_grama = 25
SENÃO SE codigo_produto >= 8 E codigo_produto <= 10
   preco_por_grama = 35    
preco_total = peso_em_gramas *preco_por_grama
ESCREVA preco_total
SE codigo_pais = 1
    imposto = 0
SENÃO SE codigo_pais = 2
    imposto = preco_total * 15/100
SENÃO SE codigo_pais = 3
    imposto = preco_total * 25/100    
ESCREVA imposto
valor_total = preco_total + imposto
ESCREVA valor_total
```
"""

codigo_produto = int(input('Digite o código do produto entre 1 a 10: '))
peso_quilos = float(input('Digite o peso do produto em quilos: '))
codigo_pais = int(input('Digite o código do país de origem entre 1 a 3: '))
peso_em_gramas = peso_quilos * 1000
print('O peso em gramas é: ', peso_em_gramas)
if codigo_produto >= 1 and codigo_produto <= 4:
   preco_por_grama = 10
elif codigo_produto >= 5 and codigo_produto <= 7:
   preco_por_grama = 25
elif codigo_produto >= 8 and codigo_produto <= 10:
   preco_por_grama = 35    
preco_total = peso_em_gramas * preco_por_grama
print('O preço total é: ', preco_total)
if codigo_pais == 1:
    imposto = 0
elif codigo_pais == 2:
    imposto = preco_total * 15/100
elif codigo_pais == 3:
    imposto = preco_total * 25/100    
print('O valor do imposto é: ', imposto)
valor_total = preco_total + imposto
print('O valor total é: ', valor_total)

"""### 27. Faça um programa que receba:
* o código do estado de origem da carga de um caminhão, supondo que a digitação do código do estado seja sempre válida, isto é, um número inteiro entre 1 e 5;
* o peso da carga do caminhão em toneladas;
* o código da carga, supondo que a digitação do código seja sempre válida, isto é, um número inteiro entre 10 e 40.

| CÓDIGO DO ESTADO| IMPOSTO|
|---|---|
|1|35%|
|2|25%|
|3|15%|
|4|5%|
|5|Isento|
>
CÓDIGO DA CARGA|PREÇO POR QUILO
---|---
10 a 20|100
21 a 30|250
31 a 40|400

Calcule e mostre:
* o peso da carga do caminhão convertido em quilos;
* o preço da carga do caminhão;
* o valor do imposto, sabendo que o imposto é cobrado sobre o preço da carga do caminhão e depende do estado de origem;
* o valor total transportado pelo caminhão, preço da carga mais imposto.

```
LEIA codigo_estado, peso_em_toneladas, codigo_carga
peso_em_quilos = peso_em_toneladas * 1000
ESCREVA peso_em_quilos
SE codigo_carga >= 10 E codigo_carga <= 20
    preco_da_carga = 100 * peso_em_quilos
SENÃO SE codigo_carga >= 21 E codigo_carga <= 30
    preco_da_carga = 250 * peso_em_quilos
SENÃO SE codigo_carga >= 31 E codigo_carga <= 40
    preco_da_carga = 340 * peso_em_quilos   
ESCREVA preco_da_carga
SE codigo_estado = 1
    imposto = 35/100 * preco_da_carga
SENÃO SE codigo_estado = 2
    imposto = 25/100 * preco_da_carga
SENÃO SE codigo_estado = 3
    imposto = 15/100 * preco_ds_carga
SENÃO SE codigo_estado = 4
    imposto = 5/100 * preco_da_carga
SENÃO SE codigo_estado = 5
    imposto = 0
ESCREVA imposto
valor_total = preco_da_carga + imposto
ESCREVA valor_total
```
"""

codigo_estado = int(input('Informe o código do estado entre 1 a 5: '))
peso_em_toneladas = float(input('Informe o peso em toneladas: '))
codigo_carga = int(input('Escolha o código da carga entre 10 e 40: '))
peso_em_quilos = peso_em_toneladas * 1000
print('O peso em quilos é: ',peso_em_quilos)
if codigo_carga >= 10 and codigo_carga <= 20:
    preco_da_carga = 100 * peso_em_quilos
elif codigo_carga >= 21 and codigo_carga <= 30:
    preco_da_carga = 250 * peso_em_quilos
elif codigo_carga >= 31 and codigo_carga <= 40:
    preco_da_carga = 340 * peso_em_quilos   
print('O preço da carga é: ', preco_da_carga)
if codigo_estado == 1:
    imposto = 35/100 * preco_da_carga
elif codigo_estado == 2:
    imposto = 25/100 * preco_da_carga
elif codigo_estado == 3:
    imposto = 15/100 * preco_ds_carga
elif codigo_estado == 4:
    imposto = 5/100 * preco_da_carga
elif codigo_estado == 5:
    imposto = 0
print('O valor do imposto é: ', imposto)
valor_total = preco_da_carga + imposto
print('O valor total é: ', valor_total)

"""### 28. Faça um programa que receba o salário base e o tempo de serviço de um funcionário. Calcule e mostre:
* O imposto, conforme a tabela a seguir.
* A gratificação, de acordo com a tabela a seguir.
* O salário líquido, ou seja, salário base menos imposto mais gratificação.
* A categoria, que está na tabela a seguir.

```
LEIA salario_base, tempo

SE salario_base < 200
    imposto = 0
SENÃO SE salario_base <= 450
    imposto = 3/100 * salario_base
SENÃO SE sal_base < 700
    imposto = 8/100 * salario_base
SENÃO
    imposto = 12/100 * salario_base
ESCREVA imposto
SE salario_base > 500
    SE tempo <= 3
         gratificacao = 20
    SENÃO 
        gratificacao = 30
SENÃO
    SE tempo <= 3
        gratificacao = 23
    SENÃO SE tempo < 6
        gratificacao = 35
    SENÃO gratificacao = 33
ESCREVA gratificacao
salario_liquido = salario_base – imposto + gratificacao
ESCREVA salario_liqquido
SE salario_liquido <= 350
    ESCREVA “Classificação A”
SENÃO SE salario_liqquido < 600
    ESCREVA “Classificação B”
SENÃO
    ESCREVA “Classificação C”
```
"""

salario_base = float(input('Informe o salário base: '))
tempo = int(input('Informe o tempo de serviço: '))
if salario_base < 200:
    imposto = 0
elif salario_base <= 450:
    imposto = 3/100 * salario_base
elif salario_base < 700:
    imposto = 8/100 * salario_base
else:
    imposto = 12/100 * salario_base
print('O valor do imposto é: ',imposto)
if salario_base > 500:
    if tempo <= 3:
         gratificacao = 20
    else: 
        gratificacao = 30
else:
    if tempo <= 3:
        gratificacao = 23
    elif tempo < 6:
        gratificacao = 35
    else:
        gratificacao = 33
print('A gratificação é: ', gratificacao)
salario_liquido = salario_base - imposto + gratificacao
print('O salário liquido é: ', salario_liquido)
if salario_liquido <= 350:
    print('Classificação A')
elif salario_liquido < 600:
    print('Classificação B')
else:
    print('Classificação C')

"""### 29. Faça um programa que:
* receba o valor do salário mínimo,
* o turno de trabalho (M — matutino; V — vespertino; ou N — noturno),
* a categoria (O — operário; G — gerente) 
* número de horas trabalhadas no mês de um funcionário. 

*Suponha a digitação apenas de dados válidos e, quando houver digitação de letras, utilize maiúsculas.*

**Calcule e mostre:**

* O coeficiente do salário, de acordo com a tabela a seguir.

TURNO DE TRABALHO|VALOR DO COEFICIENTE
---|---
M - Matutino|10% do salário mínimo
V - Vespertino|15% do salário mínimo
N - Noturno|20% do salário mínimo

* O valor do salário bruto, ou seja, o número de horas trabalhadas multiplicado pelo valor do coeficiente do salário.

* O imposto, de acordo com a tabela a seguir.

CATEGORIA| SALÁRIO BRUTO|IMPOSTO SOBRE O SALÁRIO BRUTO
---|---|---
O - Operário|>= 300,00|5%
O - Operário|< 300,00|3%
G - Gerente|>= 300,00|6%
G - Gerente|< 300,00|4%

* A gratificação, de acordo com as regras a seguir. Se o funcionário preencher todos os requisitos a seguir, sua gratificação será de 50,00; caso contrário, será de 30,00. Os requisitos são:
 * Turno: Noturno
  * Número de horas trabalhadas: Superior a 80 horas
  * O auxílio alimentação, de acordo com as seguintes regras.
* Auxilio alimentação, um terço do seu salário bruto; caso contrário, será de metade do seu salário bruto. Os requisitos são:
  * Se o funcionário preencher algum dos requisitos a seguir, seu auxílio alimentação será de 
  * Categoria: Operário
  * Coeficiente do salário: < = 25
* O salário líquido, ou seja, salário bruto menos imposto mais gratificação mais auxílio alimentação.
* A classificação, de acordo com a tabela a seguir:

SALÁRIO LÍQUIDO|MENSAGEM
---|---
Menor que 350,00|Mal remunerado
Entre 350 e 600,00|Normal
Maior que 600,00|Bem remunerado

```
LEIA salario_minino, turno, categoria, numero_de_horas_trabalhadas
SE turno = “M”
     coeficiente = 10/100 * salario_minino
SENÃO SE turno = “V”
     coeficiente = 15/100 * salario_minino
SENÃO SE turno = “N”
     coeficiente = 12/100 * salario_minino
     
ESCREVA coeficiente

salario_bruto = numero_de_horas_trabalhadas * coeficiente

ESCREVA salario_bruto

SE categoria = “O”
    SE sal_bruto >= 300
        imposto = 5/100 * sal_bruto
    SENÃO
        imposto = 3/100 * sal_bruto
SENÃO 
    SE salario_bruto >= 400
        imposto = 6/100 * salario_bruto
    SENÃO
         imposto = 4/100 * salario_bruto
         
ESCREVA imposto

SE turno = “N” E numero_de_horas_trabalhadas > 80
    gratificacao = 50
SENÃO
    gratificacao = 30
    
ESCREVA gratificacao

SE categoria = “O” OU coeficiente <= 25
    auxilio = 1/3 * salario_bruto
SENÃO
    auxilio = 1/2 * salario_bruto
    
ESCREVA auxilio

salario_liquido = salario_bruto – imposto + gratificacao + auxilio

ESCREVA salario_liquido

SE salario_liquido < 350
     ESCREVA “Mal Remunerado”
SENÃO SE salario_liquido >= 350 E salario_liqquido <= 600
     ESCREVA “Normal”
SENÃO SE salario_liquido > 600
     ESCREVA “Bem Remunerado”
```
"""

salario_minimo = float(input('Informe o salario minimo: '))
turno = str(input('Informe o turno de trabalho M ou V ou N:'))
categoria = str(input('Informe a categoria entre O ou G: '))
numero_de_horas_trabalhadas = int(input('Informe a quantidade de horas trabalhadas: '))
if turno == 'M':
     valor_coeficiente = 10 / 100 * salario_minimo
     print('O valor do coeficiente é: ', valor_coeficiente)
elif turno == 'V':
     valor_coeficiente = 15 / 100 * salario_minimo
     print('O valor do coeficiente é: ', valor_coeficiente)
elif turno == 'N':
     valor_coeficiente = 12 / 100 * salario_minimo
     print('O valor do coeficiente é: ', valor_coeficiente)
salario_bruto = numero_de_horas_trabalhadas * valor_coeficiente
print('O salário bruto é: ', salario_bruto)
if categoria == 'O':
    if salario_bruto >= 300:
        imposto = 5 / 100 * salario_bruto
    else:
        imposto = 3 / 100 * salario_bruto
else: 
    if salario_bruto >= 400:
        imposto = 6 / 100 * salario_bruto
    else:
         imposto = 4 / 100 * salario_bruto
print('O valor do imposto é: ', imposto)
if turno == 'N' and numero_de_horas_trabalhadas > 80:
    gratificacao = 50
else:
    gratificacao = 30
print('A gratificação é: ', gratificacao)
if categoria == 'O' or coeficiente <= 25:
    auxilio = 1/3 * salario_bruto
else:
    auxilio = 1/2 * salario_bruto 
print('O valor do auxilio é: ', auxilio)
salario_liquido = salario_bruto - imposto + gratificacao + auxilio
print('O salário liquido é: ', salario_liquido)
if salario_liquido < 350:
     print('Mal Remunerado')
elif salario_liquido >= 350 and salario_liquido <= 600:
     print('Normal')
elif salario_liquido > 600:
     print('Bem Remunerado')

"""### 30. Faça um programa que receba de um produto:
* o preço
* o tipo (A — alimentação; L — limpeza; e V — vestuário)
* a refrigeração (S — produto que necessita de refrigeração; e N — produto que não necessita de refrigeração) .

**Suponha que haverá apenas a digitação de dados válidos e, quando houver digitação de letras, utilize maiúsculas. Calcule e mostre:**

* O valor adicional, de acordo com a tabela a seguir:

REFRIGERAÇÃO|TIPO|PREÇO|VALOR ADICIONAL
---|---|---|---
N|A|<  15,00|2,00|
 | |>= 15,00|5,00|
 |---------|--------------|-------------------------------
 |L|< 10,00|1,50
 | |>= 10,00|2,50
  |---------|--------------|-------------------------------
 |V|< 30,00|3,00
 ||>= 30,00|2,50
  --------------------------|---------|--------------|-------------------------------
S|A||8,00
|L||0,00
|V||0,00

* O valor do imposto, de acordo com a regra a seguir.

PREÇO|PERCENTUAL SOBRE O PREÇO
---|---
< 25,00|5%
>= 25,00|8%

O preço de custo, ou seja, preço mais imposto.
O desconto, de acordo com a regra a seguir.

O produto que não preencher nenhum dos requisitos a seguir terá desconto de 3%, caso contrário, 0 (zero). Os requisitos são:
* Tipo: A
* Refrigeração: S

* O novo preço, ou seja, preço de custo mais adicional menos desconto.
* A classificação, de acordo com a regra a seguir.

NOVO PREÇO|CLASSIFICAÇÃO
---|---
<= 50,00|Barato
Entre 50,00 e 100,00|Normal
>= 100,00|Caro


```
LEIA pre, tipo, refrig
SE refrig = “N”
    SE tipo = “A”
        SE pre < 15
           valor_adic = 2
        SENÃO 
           valor_adic = 5
    SE tipo = “L”
        SE pre < 10
           valor_adic = 1.5
        SENÃO 
           valor_adic = 2.5
    SE tipo = “V”
        SE pre < 30
           valor_adic = 3
        SENÃO 
           valor_adic = 2.5
SENÃO SE tipo = “A”
    valor_adic = 8
    SE tipo = “L”
        valor_adic = 0
    SE tipo = “V”
        valor_adic = 0
ESCREVA valor_adic
SE pre < 25
    imposto = 5/100 * pré
SENÃO 
    imposto = 8/100 * pre
ESCREVA imposto
pre_custo = pre + imposto
ESCREVA pre_custo
SE tipo != “A” E refrig != “S”
  desconto = 3/100 * pre_custo
SENÃO 
  desconto = 0
ESCREVA desconto
novo_pre = pre_custo + valor_adic – desconto
ESCREVA novo_pre
SE novo_pre <= 50
    ESCREVA “Barato”
SENÃO SE novo_pre < 100
    ESCREVA “Normal”
SENÃO 
    ESCREVA “Caro”

"""

preco = float(input('Informe o preço: '))
tipo = str(input('Informe o tipo A, L ou V: '))
refrigeracao = str(input('Precisa de refrigeração? (S ou N): '))
if refrigeracao == 'N':
    if tipo == 'A':
        if preco < 15:
           valor_adicional = 2
        else: 
           valor_adicional = 5
    if tipo == 'L':
        if preco < 10:
           valor_adicional = 1.5
        else: 
           valor_adicional = 2.5
    if tipo == 'V':
        if preco < 30:
           valor_adicional = 3
        else:
           valor_adicional = 2.5
elif tipo == 'A':
    valor_adicional = 8
    if tipo == 'L':
        valor_adicional = 0
    if tipo == 'V':
        valor_adicional = 0
print('O valor adicional é: ',valor_adicional)
if preco < 25:
    imposto = 5 / 100 * preco
else:
    imposto = 8 / 100 * preco
print('O imposto é: ',imposto)
preco_custo = preco + imposto
print('O preço de custo é: ', preco_custo)
if tipo != 'A' and refrigeracao != 'S':
  desconto = 3 / 100 * preco_custo
else:
  desconto = 0
print('O desconto é: ',desconto)
novo_preco = preco_custo + valor_adicional - desconto
print('O novo preço é: ',novo_preco)
if novo_preco <= 50:
    print('Barato')
elif novo_preco < 100:
    print('Normal')
else: 
    print('Caro')

"""### 31. Faça um programa que receba a medida de um ângulo em graus. Calcule e mostre o quadrante em que se localiza esse ângulo. Considere os quadrantes da trigonometria e, para ângulos maiores que 360° ou menores que −360o, reduzí-los, mostrando também o número de voltas e o sentido da volta (horário ou anti-horário).
```
SE angulo > 360 OU angulo < -360
    voltas = parte inteira(angulo / 360)    
    angulo = RESTO(angulo / 360)
SENÃO 
    voltas = 0
SE angulo = 0 OU angulo = 90 OU angulo = 180
           OU angulo = 270 OU angulo = 360
           OU angulo = -90 OU angulo = -180
           OU angulo = -270 OU angulo = -360
  ESCREVA “Está em cima de algum dos eixos”
  SE (angulo > 0 E angulo < 90) OU (angulo < -270 E angulo > -360)
    ESCREVA “1o Quadrante”
  SENÃO SE (angulo > 90 E angulo < 180) OU (angulo < -180 E angulo > -270)
    ESCREVA “2o Quadrante”
  SENÃO SE (angulo > 180 E angulo < 270) OU (angulo < -90 E angulo > -180)
    ESCREVA “3o Quadrante”
  SENÃO SE (angulo > 270 E angulo < 360) OU (angulo < 0 E angulo > -90)
    ESCREVA “4o Quadrante”
  ESCREVA voltas, “ volta(s) no sentido “
SE angulo < 0
    ESCREVA “horário”
SENÃO 
    ESCREVA “anti-horário”
```
"""

angulo = int(input('Informe o ângulo em graus: '))
if angulo > 360 or angulo < -360:
    voltas = angulo // 360   
    angulo = angulo % 360
else: 
    voltas = 0
if angulo == 0 or angulo == 90 or angulo == 180 or angulo == 270 or angulo == 360 or angulo == -90 or angulo == -180 or angulo == -270 or angulo == -360:
    print('Está em cima de algum dos eixos')
    if (angulo > 0 and angulo < 90) or (angulo < -270 and angulo > -360):
        print('1º Quadrante')
    elif (angulo > 90 and angulo < 180) or (angulo < -180 and angulo > -270):
        print('2º Quadrante')
    elif (angulo > 180 and angulo < 270) or (angulo < -90 and angulo > -180):
        print('3º Quadrante')
    elif (angulo > 270 and angulo < 360) or (angulo < 0 and angulo > -90):
        print('4º Quadrante')
    print('Voltas no sentido: ', voltas)
if angulo < 0:
    print('horário')
else: 
    print('anti-horário')